### ISSUE TITLE
Delete Item

### ISSUE THREAD

**Issue by Elgubar** [VanillaPlusPlus/VPP-Admin-Tools#10]
Hey mate,

Some spawn item couldn't be delete.
For some items, take it in hand and throw it will work to delete them after that. 
But for others like tent that we can't throw, no way do delete it. Even in pack or deployed :/

Best regards.

**Comment by Elgubar** [comment]
I confirm, mostly for tent. This is a bit annoying for admin if we can't delete tent ;)

Hope you can fix this.

**Comment by Elgubar** [comment]
Other little issue : When you create a weapon preset, the magazine don't attach to the "parent" and don't spawn at all.

**Comment by GravityWolfNotAmused** [comment]
Magazines do not work that way in DayZ.

**Comment by Elgubar** [comment]
Yes it does. I can plane to spawn it on weapon in randomspawn files. If it
works this way, it coup work on your modnfor sure ;)

**Comment by GravityWolfNotAmused** [comment]
No, scripting is way different in outcome than configuration files that are made by DayZ.

**Comment by GravityWolfNotAmused** [comment]
Sorry, dual topic. I'll figure out something if anything for tents, but I am not about to let mags get stuck in weapons. Thank you for the report <3

**Comment by Elgubar** [comment]
Hi man,

Tent is deletable by the esp menu, but not with quick shortcut

2019-09-05 20:37 UTC+02:00, Larry <notifications@github.com>:
> Sorry, dual topic. I'll figure out something if anything for tents, but I am
> not about to let mags get stuck in weapons. Thank you for the report <3
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/VanillaPlusPlus/VPP-Admin-Tools/issues/10#issuecomment-528518184


-- 
*Elgubar* .
