### ISSUE TITLE
Add a Password - doesnt accept - scrambles password

### ISSUE THREAD

**Issue by jnielsen19** [VanillaPlusPlus/VPP-Admin-Tools#100]
so i add my chosen password to credentials.txt after adding my steam64id into the superadmin.txt file. I then join the server attempt to open the menu - password prompt opens as expected - i enter my password - it doesnt accept it - and then I check the credentials.txt file and it changes to a long sequence of random characters.

**Comment by GravityWolfNotAmused** [comment]
I know that it has to change the password to make sure that the raw password is not...raw. 💯 

But, I think @Da0ne has a better way to explain it.

**Comment by jnielsen19** [comment]
> I know that it has to change the password to make sure that the raw password is not...raw. 💯
> 
> But, I think @Da0ne has a better way to explain it.

Thank you for the quick reply - so should I try the new 'scrambled' password

**Comment by jnielsen19** [comment]
update:  i have tried the scrambled password or what was in the txt file and that doesnt work either (apologies im new and learning this stuff)

**Comment by Da0ne** [comment]
You are not meant to use the scrambled password. The text file explains it clearly. Delete the file and let it regenerate again. Type a password on the very first line with no spaces between the characters. Save it, restart the server and your game. Use the exact thing you wrote to log in. If this still is not working, disable the feature entirely by adding vppDisablePassword = 1; to your serverDZ.cfg

**Comment by jnielsen19** [comment]
> You are not meant to use the scrambled password. The text file explains it clearly. Delete the file and let it regenerate again. Type a password on the very first line with no spaces between the characters. Save it, restart the server and your game. Use the exact thing you wrote to log in. If this still is not working, disable the feature entirely by adding vppDisablePassword = 1; to your serverDZ.cfg

Hi @Da0ne - thank you for your help - the only problem I am having with this is Im on nitrado so I have limited control over my server. I have restarted it a couple of times and let the file regenerate and and entered a new password and restart the server. Still no luck but im gonna try again (will update in a few minutes)

**Comment by Da0ne** [comment]
You have access to the serverDZ.cfg you can at least at new custom parameters. If not, i highly recommend you don't use that service and overpay for restricted access

**Comment by jnielsen19** [comment]
Thats what I was thinking - I have been considering switching to a VPS anyway - might be the time to do it - thank you for the help

**Comment by jnielsen19** [comment]
alright @Da0ne thank you very much for your help - disabled to the password - ill go from there
