### ISSUE TITLE
Profiles folder not clear

### ISSUE THREAD

**Issue by Datalus848** [VanillaPlusPlus/VPP-Admin-Tools#103]
The instructions on the steam page say “navigate to Profiles/VPPAdminTools/Permissions...”. Could you please clarify this isn’t very clear where this folder is. Sorry if I’m asking a dumb question but I’m new to discord and I’m new to steam. 

I tried to ask for help on your discord, but I couldn’t type anywhere on the server. I saw that gravity wolf was online, so I asked him for help. I tried to explain to him that I’m still learning to use discord. He told me that I needed a role, but I told him I didn’t know how to do that. He was very rude and kicked me off the server and blocked me. 
I was just trying to get some help. He made me feel terrible.

**Comment by Da0ne** [comment]
figure it out lol

**Comment by Datalus848** [comment]
You guys are rude

**Comment by Da0ne** [comment]
No, i don't think so.
Profiles folder is where mod configurations are saved, its the folder that is auto created on server start. Its named diffrently to each server according to whatever the startup parameter -profiles=FOLDERNAME is set to be. Profiles folder is also the folder that contains all the log files generated by DayZ Server.

If you are using a GSP (Game Service Provider, web panel) that is already setup for you, you need to find where it is / what its called. Typically you can find that in the file browser of the web panel.

**Comment by dummerfranz** [comment]
> No, i don't think so. Profiles folder is where mod configurations are saved, its the folder that is auto created on server start. Its named diffrently to each server according to whatever the startup parameter -profiles=FOLDERNAME is set to be. Profiles folder is also the folder that contains all the log files generated by DayZ Server.
> 
> If you are using a GSP (Game Service Provider, web panel) that is already setup for you, you need to find where it is / what its called. Typically you can find that in the file browser of the web panel.



Admin should add this into README!
-profile parameter is mostly not set....
