### ISSUE TITLE
Admin menu won't open

### ISSUE THREAD

**Issue by JuliaCarrilo** [VanillaPlusPlus/VPP-Admin-Tools#107]
I can't get the admin menu to open.

Added me in the superadmin.txt (Steam 64 ID)
Mod is added to the client via DayZ launcher
Mod is added to the server and included in command-line options
Bikeys are copied e t c.
I log in as admin (#login XXXX which works)
I set the key with Insert (even tried to change it)
I press the key to open the Admin menu
Nothing happens. Is there a debug log somewhere so I can see where it goes wrong?

**Comment by GravityWolfNotAmused** [comment]
#login is not needed to use the admin tool.

Yes, the logs are in the VPPAdminTool folder in your profiles folder.
Can I see your superadmins.txt?
Did you set a password for the admin tool in your configuration file?
Can I see your server's command line?

**Comment by JuliaCarrilo** [comment]
SuperAdmin only has this (my ID?)

76561199001017177
I did set but it changed to numbers? And I was able to log on the normal admin using my server password.
@VPPAdminTools;@Basic Map;@Community-Online-Tools;@DayZ-Dog;@FS Translation;@Bed-Respawning;@CF;@Code Lock;

**Comment by GravityWolfNotAmused** [comment]
It seems that your order is wrong. Also, the names of the folders should match what is in your command line arguments, and by default CF is not `@cf`.

Firstly, put CF in front of VPP, we need it to load first.

**Comment by JuliaCarrilo** [comment]
Ok

**Comment by JuliaCarrilo** [comment]
Doing it now.

**Comment by JuliaCarrilo** [comment]
Did not work.. do you have discord? Maybe can look at my screen?

**Comment by GravityWolfNotAmused** [comment]
https://discord.gg/MWYa7zQn

**Comment by GravityWolfNotAmused** [comment]
Be sure to set a role, and then we can join voice and figure it out.
