### ISSUE TITLE
ESP Skeleton mode

### ISSUE THREAD

**Issue by Snowmanko** [VanillaPlusPlus/VPP-Admin-Tools#109]
Does this mode include possiblity to spectate players with ESP Skeleton mode on like in Community Online Tools? So admin can see player skeletons behind walls and watch their behaviour to detect cheaters ? THNKS!

**Comment by Da0ne** [comment]
> Does this mode include possiblity to spectate players with ESP Skeleton mode on like in Community Online Tools? So admin can see player skeletons behind walls and watch their behaviour to detect cheaters ? THNKS!

Yes. Check keybinds ingame for how to activate. Default key is Y (must have permissions and the tool toggled)
