### ISSUE TITLE
Webhook has wrong url, and how to customize server name?

### ISSUE THREAD

**Issue by bluetidepro** [VanillaPlusPlus/VPP-Admin-Tools#112]
Just an FYI, on this line, it links to the OLD steam URL: https://github.com/VanillaPlusPlus/VPP-Admin-Tools/blob/93bf387be9c88a095e8d453073c750c5af97a307/4_World/VPPAdminTools/Plugins/PluginBase/WebHooksManager/Classes/WebHookMessageBase.c#L98 (The new URL for VPP is `https://steamcommunity.com/sharedfiles/filedetails/?id=1828439124`)

Secondly, how do I customize the "SERVERNAME" in webbooks? Right now, it does: `The DayZ Server EXAMPLENAME has booted-up successfully!` - so I wasn't sure where I could customize the `EXAMPLENAME ` part? I didn't see it in the config at all.

**Comment by Da0ne** [comment]
Hey thanks for that!

You edit your server name in your serverDZ.cfg

**Comment by bluetidepro** [comment]
Perfect, thanks!
