### ISSUE TITLE
LargeTentBackPack

### ISSUE THREAD

**Issue by johnstonecooper484** [VanillaPlusPlus/VPP-Admin-Tools#114]
Anytime I or anyone uses the VPP admin tool and accidentally Scrolls over the item called large tent backpack game window close literally crashes the game. Could this be fixed? Or is there a way for me or other people remove this from the list. Manually. So this does not happen? Or is this from another mod. And if so can I please have the link so I can stop crashing thank you have a nice day.

**Comment by EDTDev** [comment]
Funny story that object has been a pain in my but for a long time. It's not VPP, It's part of a mod pack or something. As I have been trying to find and remove it long before I started using VPP.
I do have a workaround And time you search large or backpack Turn Off your Preview and you will not crash scrolling over it.

If anything I would Request the Dev's of VPP Add a Filter to Block the name from showing in the Object SPawner List.

I love this Mod, Thank you, guys.
