### ISSUE TITLE
 Bleeding problem

### ISSUE THREAD

**Issue by Qpr1me** [VanillaPlusPlus/VPP-Admin-Tools#12]
Good day, players on the server who are not subscribed to the VPP-Admin-Tools mod have 18 bleedings and the character becomes like a fountain, but health does not decrease, if you subscribe to the mod, this bug disappears, what could be the problem and how fix it?

"-mod=DZM_Notifications;VPPAdminTools"

![20190910204714_1](https://user-images.githubusercontent.com/54238266/64637308-2cedf880-d40c-11e9-9043-d9e767afe100.jpg)

**Comment by GravityWolfNotAmused** [comment]
All clients must be subscribed to the mod.

**Comment by GravityWolfNotAmused** [comment]
Also, where is CF in your mod list? That's needed. Are you running these mods unpacked?

**Comment by Qpr1me** [comment]
Sorry, I did not correctly copy : "-mod=DZM_Notifications;VPPAdminTools;CF" 

Now it is imperative that everyone is signed, right? this was not required before ... Just new people who go to the server do not understand what the blood is from.

**Comment by GravityWolfNotAmused** [comment]
Yes, you should be verifying signatures on your server, and if you are not you could run into issues. The blood isn't something we changed or even touched in any way, so it's beyond me.
