### ISSUE TITLE
ESP problem

### ISSUE THREAD

**Issue by jobthe** [VanillaPlusPlus/VPP-Admin-Tools#126]
Hello, ESP does not show transport and other things underwater
![Screenshot_220](https://user-images.githubusercontent.com/117097134/199034165-3b18b48d-d64a-44ae-9537-14c63226cfef.png)
In the photo, the ATV that is standing on the ground is displayed in ESP
And the ATV that is under water is not displayed in ESP

**Comment by Da0ne** [comment]
Issue is resolved, fix coming soon.
