### ISSUE TITLE
File path issue

### ISSUE THREAD

**Issue by MedicMike725** [VanillaPlusPlus/VPP-Admin-Tools#127]
After the update for DayZ and steam this morning the server refuses to update the mod. I deleted and tried to reinstall it. It is continuing to get file path issues when downloading.

**Comment by GravityWolfNotAmused** [comment]
We don't control that, manually update the mod.

**Comment by MedicMike725** [comment]
I tried to do that, and it refuses to update. I even manually pulled it from Steam with no luck.

**Comment by spookdregher** [comment]
same problem for me, removed mod and have to manually add again, all other mods are updateable and downloadable

**Comment by MedicMike725** [comment]
Still refused to download. It goes through 5 tries and then fails.

**Comment by MedicMike725** [comment]
steam is full of failing downloads for server owners after this morning's update. at this point it has surpassed my ability to figure it out.

**Comment by spookdregher** [comment]
Have to wait for an update or remote into server files and add manually

**Comment by GravityWolfNotAmused** [comment]
This is all in steam's court a believe, so we cannot do anything about you failing to download mods, we don't control that.

**Comment by MedicMike725** [comment]
sounds good I appreciate the feedback thanks

**Comment by spookdregher** [comment]
should be good to go now, looks like steam fixed on their end
