### ISSUE TITLE
Webhook not showing joining message

### ISSUE THREAD

**Issue by Bananenbaas** [VanillaPlusPlus/VPP-Admin-Tools#128]
Hi! 

Since the last update (from 17-11-2022) the webhooks on my server don't show when a player joins the server. Only when someone disconnects the messages are being send. I've tried resinstalling the mod, using a new WebHook.json and using another webhook URL but still only exit messages seem to be send. 

Do other people get this too?

**Comment by Da0ne** [comment]
Known issue, planned update soon :) 
Thanks for reporting it!

**Comment by Bananenbaas** [comment]
Thanks for the update! Will keep an eye on it!

**Comment by Neorilas** [comment]
Still not working the loging logs.

**Comment by tsyrak** [comment]
Not sure If I should have started a new thread reporting this also, I did used to see the webhooks etc, but now I dont.
Tried the usual .,.
