### ISSUE TITLE
Admin fix position

### ISSUE THREAD

**Issue by Elgubar** [VanillaPlusPlus/VPP-Admin-Tools#13]
Hi,

Is there a way to player be fixe when moving in freecam ?
Actually the admin who uses this move all around.
I know if keybind is not the same it works, but isn't there another way to do this ?

Thanks for answer.
(once again, really love this admin mod even if it makes crash the game sometimes)

**Comment by Da0ne** [comment]
Latest change log is available in our Discord,GitHub and on Steam. 
Freecam issue and the client crashing while using some menus were resolved.

[ PatchNotes:](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/releases/tag/1.0.1)
