### ISSUE TITLE
After i delete Vanilla gate 

### ISSUE THREAD

**Issue by Mikike982** [VanillaPlusPlus/VPP-Admin-Tools#134]
After i use VPP admin tools and delete the  vanilla gate. . The barbed Wier is invisible and it hurts the character

**Comment by Mikike982** [comment]
Please help me

**Comment by Greg89hun** [comment]
A server restart fix this bug.

**Comment by Greg89hun** [comment]
Amúgy valami nagyobb projekt lesz ez, vagy kisebb szerver baráti körnek, esetleg hobbi szerver?

**Comment by Mikike982** [comment]
Ez a szerver már megy A neve 
Nostalgia Plus Magyar

Próbálunk népszerűsíteni csak hát nagyon szét van szorodva a magyar közösség, hát mit mondjak. én csak admin vagyok a szeron.

Dc https://discord.gg/mPshVUNb7n

**Comment by Greg89hun** [comment]
Köszi az infót.
Lesz egy kis szabadidőm végre, akkor meglesem. :)

**Comment by Mikike982** [comment]
Nyugodtan, bár nem vagyunk profik.  Vannak hibák a szerveren. Szebb estéken van kb 9-12 player , máskor 2-4.

**Comment by Greg89hun** [comment]
DayZ szervert bug/egyéb hiba nélkül még nem láttam, szóval nincs azzal gond.
A playerszám meg sajna ilyen. Mi is, mikor még több időnk volt és csináltunk szervert, próbáltunk megfelelni a játékosok igényeinek, de ez lehetetlen küldetés. :D Külföldi playerünk több volt, mint magyar.

**Comment by Mikike982** [comment]
Próbálunk nem a játékosok igénye szerint alakítani 1-2 dolgot leszámítva.Ne menjen el pve be a szerver.

**Comment by Mikike982** [comment]
Ez az 1.20 hozott jó pár idegesítő bugot... A stamina nálunk modolt volt

**Comment by Mikike982** [comment]
Ugy kêpzeld el patch wlött volt valami 
Röhögni fogsz, 36 ezer hunting backpack spawnolt ... 🤣

**Comment by Greg89hun** [comment]
Az kemény. Gondolom akkor mindenhol hátizsák volt. :D
