### ISSUE TITLE
DayZ 1.20 Issue

### ISSUE THREAD

**Issue by CoreySFLightman** [VanillaPlusPlus/VPP-Admin-Tools#137]
Hello there.

I'm trying to execute DayZDiag_x64.exe in server mode with VPPAdminTools and I have this:
![изображение](https://user-images.githubusercontent.com/45088993/219864104-4d92bb9d-ab0a-4800-b63b-2ff3f6d638ae.png)

VPPAdminTools/5_Mission/vppadmintools\gui\submenus\menuplayermanager\menuplayermanager.c(71): Callbacks do not properly support overloaded methods 'OnUpdate'

Could you help me to solve this issue?

Sincerely,
SharkAttack

**Comment by Da0ne** [comment]
add `-newErrorsAreWarnings = 1` to startup command parameters.

**Comment by CoreySFLightman** [comment]
> 

Thank you! It works!
