### ISSUE TITLE
Ajuda urgente!

### ISSUE THREAD

**Issue by ramonor** [VanillaPlusPlus/VPP-Admin-Tools#138]
The panel opens normally, but nothing appears written on the buttons

`Log D:\SteamLibrary\steamapps\common\DayZServer\ServerProfile\script_2023-02-24_06-50-48.log started at 24.02. 06:50:50

SCRIPT       : Registered 337 temporary action enum(s), UAN==337
SCRIPT       : ... Backlit Effects Enabled
SCRIPT       : VPPNotificationManager()
SCRIPT       : [VPPAT] Internal VPPNotifications module loaded!
SCRIPT       : [DayZ Game]:: DayZGame(): Initializing V++ Admin Tools.
SCRIPT       : Default Mission: $saves:VPPDebugMissions/Debug.chernarusplus exists!
SCRIPT       : Default Mission: $saves:VPPDebugMissions/Debug.enoch exists!
SCRIPT    (W): @"VPPAdminTools/4_World/vppadmintools\plugins\pluginbase\webhooksmanager\classes\webhookmessagebase.c,53": Possible variable name conflict 'title'
SCRIPT    (W): @"VPPAdminTools/4_World/vppadmintools\plugins\pluginbase\webhooksmanager\classes\webhookmessagebase.c,53": Possible variable name conflict 'color'
SCRIPT    (W): @"VPPAdminTools/4_World/vppadmintools\plugins\pluginbase\webhooksmanager\classes\messagetypes\joinleavemessage.c,7": Possible variable name conflict 'guid'
SCRIPT    (W): @"VPPAdminTools/4_World/vppadmintools\plugins\pluginbase\webhooksmanager\classes\messagetypes\joinleavemessage.c,7": Possible variable name conflict 'details'
SCRIPT    (W): @"VPPAdminTools/4_World/vppadmintools\plugins\pluginbase\admintools\admintools.c,60": No need to use 'Cast' for up-casting
SCRIPT    (W): @"VPPAdminTools/5_Mission/vppadmintools\gui\submenus\menuobjectmanager\menuobjectmanager.c,203": Missing ';' at the end of line
SCRIPT    (W): @"VPPAdminTools/5_Mission/vppadmintools\gui\vppadminhud.c,126": Unsafe down-casting, use 'MenuObjectManager.Cast' for safe down-casting
SCRIPT    (W): @"VPPAdminTools/5_Mission/vppadmintools\gui\submenus\menuesptools\esptoolsmenu.c,580": Unsafe down-casting, use 'EntityAI.Cast' for safe down-casting
SCRIPT    (W): @"VPPAdminTools/5_Mission/vppadmintools\gui\submenus\menuplayermanager\menuplayermanager.c,71": FIX-ME: Callbacks do not properly support overloaded methods 'OnUpdate'
SCRIPT    (W): @"VPPAdminTools/5_Mission/vppadmintools\missiondebug.c,38": Unsafe down-casting, use 'PlayerBase.Cast' for safe down-casting
SCRIPT       : Vanilla++ AdminTools Plugins Registering..
SCRIPT       : [MissionServer] OnInit - Server
SCRIPT       : [MissionServer] OnMissionStart - Server
SCRIPT       : string dirtyName = 'Alpha'
SCRIPT       : m_LoginTimeMs: 16200
SCRIPT       : [MissionServer] OnMissionFinish - Server
SCRIPT       : ~DayZGame()
`

this is what appears in the log! I already reinstalled the game and the server and the problem continues
[https://imgur.com/a/wWDz7Bm](url)

**Comment by ZNServer** [comment]
I have the same problem on my server.

**Comment by ZNServer** [comment]
I managed to solve it guys, just enter the server, change the language to English and apply. Then close the game and open it again.
