### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Ilya70007** [VanillaPlusPlus/VPP-Admin-Tools#14]
I've set up offline server, installed @CF, @DZM_Notifications and @VPPAdminTools, server runs smoothly. But, when I try logging in game, when countdown to spawn reaches 2 secs, the game crashes. No other mods installed, need help.

Edit:
Message from server console: Player kicked from server: 3 (Bad Packet)

**Comment by GravityWolfNotAmused** [comment]
Look like a network problem, huh.

**Comment by Ilya70007** [comment]
I've played on the same server without VPP, didn't have any problems whatsoever

**Comment by Ilya70007** [comment]
btw, there's crash dialog:

![image](https://user-images.githubusercontent.com/25904893/64925568-ef261100-d80b-11e9-9e7c-3ac32ecbed96.png)

**Comment by GravityWolfNotAmused** [comment]
Any sort of crash log for the client?

**Comment by Ilya70007** [comment]
I can send you minidump that was just created

**Comment by Ilya70007** [comment]
Ok, so, I've set all mods in launch options in launcher and I've joined the server. Now I have another problem: I can't open menu, I press insert and nothing happens.

**Comment by GravityWolfNotAmused** [comment]
<3
