### ISSUE TITLE
Bug when opening the panel in game

### ISSUE THREAD

**Issue by ZNServer** [VanillaPlusPlus/VPP-Admin-Tools#142]
When I open the ADM panel in the game it appears all misconfigured, the texts don't appear, only the squares to click on and for that reason I can't know what I'm doing.
Can anyone help?
Here's a link to the image of how the panel looks
https://imgur.com/a/wWDz7Bm

**Comment by ZNServer** [comment]
https://imgur.com/a/wWDz7Bm

**Comment by pabloriguetto** [comment]
I have the same bug

**Comment by ZNServer** [comment]
> eu tenho o mesmo bug

I managed to solve it guys, just enter the server, change the language to English and apply. Then close the game and open it again.
