### ISSUE TITLE
Specific ESP Classes Range Limit

### ISSUE THREAD

**Issue by talkinggoat** [VanillaPlusPlus/VPP-Admin-Tools#147]
When calling specific item classes, such as Whetstone or MetalPlate, they seem to have a limit of 159 meters, while other major classes, such as ItemBase go out to whatever is set in ESP. Is there a way to fix this?

**Comment by GravityWolfNotAmused** [comment]
I don't believe this is intentional by our mod, and is likely a player bubble issue.

**Comment by talkinggoat** [comment]
I am inclined to agree with you. I increased the networkRangeNear = 500; up from 150 and it started working closer to what's expected. There seems to be a "grace" area between the networkRangeNear and + 50m. In this case, items appear at 499 and disappear at 550m... but why do the main classes show the items, but the individual classes don't? Some classes, like the barrel, work as expected. Is this something the mod can override?

**Comment by GravityWolfNotAmused** [comment]
I assume that this would be engine side, and something we can not control beyond that. If anything, it'd be in each items configuration in it's definition. I'd check with the modders discord to see if more people may have an idea of why.
