### ISSUE TITLE
"multiple declarations of "permission manager" then the mod crashes my game

### ISSUE THREAD

**Issue by toastysovet** [VanillaPlusPlus/VPP-Admin-Tools#15]
here's the message I keep getting on my pc when I start dayz
![image](https://user-images.githubusercontent.com/55418248/65002555-4af2a780-d8a9-11e9-8cdc-ab28c0a53c41.png)

**Comment by Da0ne** [comment]
Could you please post your startup command line?
The issue seems to be with **loading other mods**, do you have any other admin tool set **loaded** that is **not** VPPAdminTools?

**Comment by toastysovet** [comment]
let me double check but I don't think so

**Comment by Da0ne** [comment]
There is also a possibility that you have two or more copies of the VPPAdminTools that are getting loaded.

**Comment by toastysovet** [comment]
no no other admin tools and I am not sure how to get the start up command line
and how could I tell if there are more than one set of mods getting loaded

**Comment by GravityWolfNotAmused** [comment]
Who is your hosting provider, or are you just using the vanilla server utilities from steam?

**Comment by toastysovet** [comment]
that isn't hosting a server that's just trying to launch the game

**Comment by toastysovet** [comment]
the mod is required for some servers and it keeps crashing whenever I launch from both launchers

**Comment by Da0ne** [comment]
If you are using the vanilla DayZ launcher (not community made DayZ SA Launcher) make sure you have no extra command lines active that add mods eg: 
![image](https://user-images.githubusercontent.com/38754008/65002811-d6ffe000-d938-11e9-9c6e-98d0e233a020.png)

You can also unsubscribe from the mod, then resub to download it again. In case steam had not updated correctly.

Also check your mod list if you are using the vanilla DayZ launcher, make sure that you have loaded the correct mods.

To clarify , this issue is to do within your game client right? and the server is okay?

**Comment by toastysovet** [comment]
yes the server is fine I was playing fine earlier the it updated for some reason and that happened
![image](https://user-images.githubusercontent.com/55418248/65002948-0a942900-d8ab-11e9-8508-ea97ee5edd71.png)

**Comment by Da0ne** [comment]
the community made DZSA Launcher can also have custom launch param, make sure those are not actively loading wrong mods. 
![image](https://user-images.githubusercontent.com/38754008/65002964-9bb1e100-d939-11e9-9669-e7ff351a27b0.png)


Your final option to try, unsub from the mod. And then resub for a fresh download. Do this via steam

**Comment by GravityWolfNotAmused** [comment]
Also make sure you remove the content from your subscription page, but also check the !workshop folder to be sure everything was removed properly.

**Comment by toastysovet** [comment]
![image](https://user-images.githubusercontent.com/55418248/65003002-4fb85b00-d8ab-11e9-81a3-2a41d8da4cf5.png)
I have unsubbed and resubbed a few times

**Comment by GravityWolfNotAmused** [comment]
Which way are you trying to join the server? Vanilla, or DayZSA?

**Comment by toastysovet** [comment]
ive done both it crashes occationally with the DZSA

**Comment by GravityWolfNotAmused** [comment]
Not with vanilla? I'd delete the admin tools in your !dzsa folder on your client, and add the one from the workshop or redownload. This is extremely odd.

**Comment by GravityWolfNotAmused** [comment]
Toasty, are you still there?

**Comment by CBAPOr** [comment]
![1231](https://user-images.githubusercontent.com/55498576/65156678-2a0c8c80-da38-11e9-941f-b08a0cf2ea80.png)
What is my problem?

**Comment by Da0ne** [comment]
You are missing/not loading the dependency mods.
![image](https://user-images.githubusercontent.com/38754008/65158212-51ce1580-da75-11e9-8f37-5153b7ee8430.png)

Make sure you have added those to your startup command line

**Comment by CBAPOr** [comment]
> Вы отсутствуете / не загружаете моды зависимостей.
> ![образ](https://user-images.githubusercontent.com/38754008/65158212-51ce1580-da75-11e9-8f37-5153b7ee8430.png)
> 
> Убедитесь, что вы добавили их в командную строку запуска

Yes, I was not attentive, and then I got an error 41 ((what should I enter in init.c

**Comment by CBAPOr** [comment]
I also dealt with this. I deleted the file and updated it.

**Comment by CBAPOr** [comment]
I installed the mod, but I can’t build, what is the reason?

**Comment by GravityWolfNotAmused** [comment]
Show me menu for building

**Comment by GravityWolfNotAmused** [comment]
I then can tell you why

**Comment by CBAPOr** [comment]
It seems to be sorted out.  It remains only to understand how to tilt objects at an angle of 10-90 degrees.

**Comment by GravityWolfNotAmused** [comment]
Use the information panel for the object.
