### ISSUE TITLE
![1231](https://user-images.githubusercontent.com/55498576/65156678-2a0c8c80-da38-11e9-941f-b08a0cf2ea80.png)

### ISSUE THREAD

**Issue by CBAPOr** [VanillaPlusPlus/VPP-Admin-Tools#16]

**Comment by CBAPOr** [comment]
![Снимок](https://user-images.githubusercontent.com/55498576/65158104-7a84e980-da3a-11e9-93c6-74066364a228.PNG)
> What is my problem?
> VPPAdminTools / Permissions / SuperAdmins and where is this folder?

**Comment by GravityWolfNotAmused** [comment]
That's an issue with your init.c, and the folder is located in your profiles folder.
