### ISSUE TITLE
Error when loading into the game

### ISSUE THREAD

**Issue by M1N3R-MAN** [VanillaPlusPlus/VPP-Admin-Tools#17]
When starting up the game I get a Compile error:

Can't compile "World" script module!
VPPAdminTools/4_World/plugins\pluginsbase\permissionmanager\permissionmanager.c(8): Multiple declaration of class 'PermissionManager'

I have no experience when it comes to making mods so all of that means absolutly nothing to me. I followed the installation instruction but if I still managed to something wrong then I have no idea where.
![image](https://user-images.githubusercontent.com/18738425/66270214-b089e200-e81e-11e9-938e-0bd0c85dcc2b.png)

**Comment by Da0ne** [comment]
You have other admin tools that are loaded. Remove COT or any other admin tools. That is the cause of incompatibility

**Comment by M1N3R-MAN** [comment]
-dayzserver=DayZServer.exe -scrAllowFileWrite -mod=@BaseFurnitureMods2;@CheckPulse;@CloseOpenAnywhere;@DayZExpansionChat;@EarPlugs;@InventoryPlus;@Killfeed;@ServerInformationPanel;@WindstridesClothingPack;@ZeroyFishingZ;@QuieterSuppressors;@DeerIsle;@DayzNavigation;@CF;@VanillaPlusPlusMap;@IncreasedLumens;@BaseFortifications;@BaseStorage;@BuildAnywhere;@BulletStacksPlusPlus;@CamoNetPlus;@DisableBaseDestruction;@GoreZ;@SummerChernarus;@PartyMe;@DmnsExtraWeaponZ;@ItemSizeTweak;@MosinScope;@SQUADMSFC;@CodeLock:@FlipTrasnport;@IntenzLeaderboard;@VPPAdminTools;@VPPNotifications

Not sure which one of these is another admin tool?

**Comment by Da0ne** [comment]
There must be a duplicate of the mod (VPPAdminTools). Or one of those mods in your list is incompatible.
