### ISSUE TITLE
Repeatable Crash to Desk top and ESP function issues

### ISSUE THREAD

**Issue by TheGL** [VanillaPlusPlus/VPP-Admin-Tools#18]
When double clicking on the map to teleport basically anywhere the client crashes to desktop and spits out this 

 NULL pointer to instance
Class:      'MenuTeleportManager'
Function: 'UpdateMap'
Stack trace:
VPPAdminTools/5_Mission/gui\submenus\menuteleportmanager\menuteleportmanager.c:135
JM/CF/Scripts/3_Game/communityframework\rpc\rpcmanager.c:251
scripts/3_Game/dayzgame.c:2342

This crash is 100% repeatable for me. It also only seems to affect the super admins

The ESP toggle function does not persist when using the ESC key to back out of the admin UI, it does however persist if you use the toggle admin key to back out of the UI.

So far I have verified my game files, I have reinstalled the game itself, I have also removed every single mod and re subscribed to them. The only thing that fixes the issue with VPP admin tools is when I remove the Codlock mod.

**Comment by GravityWolfNotAmused** [comment]
Thank you for the bug report, I've looked into the error that you've mentioned, and it seems to be the map widget being null. I've put a null check in place to be sure that it doesn't hang up at that point; however, I will need you to do whatever you can after the update is pushed to make this happen again.

Second, the ESP system is controlled by the GUI window, and when you press escape it's not a hide function, it's a close. Hiding it would be pressing the toggle key again. Without the menu being open in someway the update loop cannot trigger.
