### ISSUE TITLE
Server Launch Error - Cant Compile "Game" ********

### ISSUE THREAD

**Issue by Dpatau** [VanillaPlusPlus/VPP-Admin-Tools#19]
![64276460-b30fc800-cf50-11e9-819e-f366d0924d51](https://user-images.githubusercontent.com/10263463/68200753-690a9780-0010-11ea-8aba-0573232893f9.png)
 can anyone help with how to fix this please 

iv seen someone else have the issue but didnt explain how they fixed it

**Comment by GravityWolfNotAmused** [comment]
Missing the mod known as CF. Check the steam workshop.
