### ISSUE TITLE
Dayz server gives a error after closing/automatic restart/crashes.

### ISSUE THREAD

**Issue by Gypopo** [VanillaPlusPlus/VPP-Admin-Tools#20]
Hello,

First of all, great mod, I can build custom builds with it and more.

The problem is that my dayz server throws out an error when I manually close the game or when it crashes or when it automaticly restarts, simply if it closes the dayz server.

Well, its not that big of a deal, I just have to click on "ok" but I have planned to make this a public dayz server so when Im asleep or Im not online then when the server automaticly restarts it won't start up the server again after closing it bcs the error pops up and someone has to click "ok" before it will start back up. + Its anoying if I have to click on "ok" every time.

This is the error: The instruction at 0x0xxxxxxxxxxxxx referenced memory at 0x000fffffffffffffff The memory could not be written.

I noticed that the error is there from when I added the VPP-Admin-Tools mod and created some custom objects.

So can someone pleasse help me with this, I already tried to update the required dll files/I gave the server more RAM/updated the server files/followed this guide: https://support.steampowered.com/kb_article.php?ref=1274-uohk-5653&l=dutch/removed "Community-Online-Tools" files but after all that it still does not work.

Im running the dayz server on my own deticated server, 25 GB RAM/12 cores/130 GB free space(this are my specs from my dayz server)

Thx,
Gypopo

**Comment by GravityWolfNotAmused** [comment]
That's really strange; however, a memory error is not something that we can track down.
