### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by HotNachos** [VanillaPlusPlus/VPP-Admin-Tools#21]
My client crashes 2 seconds before server connection. 

----------------------
Process exit
----------------------
Exit code:           0xC0000005 - STATUS_ACCESS_VIOLATION
Running time:        00:02:17.8050746

----------------------
System information
----------------------
Date:                2019-12-01 19:10:09 / 2019-12-01 14:10:09 -05
Current dir:         D:\Program Files (x86)\Steam\steamapps\common\DayZ
Command line:        "D:\Program Files (x86)\Steam\steamapps\common\DayZ\DayZLauncher.exe"
CLR version:         4.0.30319.42000
OS Version:          10.0.17763.0 (Microsoft Windows NT 10.0.17763.0)
OS 64 bit:           True
Process 64 bit:      False
Culture:             en-US
UI Culture:          en-US

----------------------
Last game report
----------------------
not provided

**Comment by GravityWolfNotAmused** [comment]
Clear out your client profile of logs, or set a profile for your client.

**Comment by HotNachos** [comment]
Where are they located?

**Comment by GravityWolfNotAmused** [comment]
In your local app data.

**Comment by HotNachos** [comment]
Still crashing. What is the exact location of the client profile of logs.
(I'm running a private server ran from my PC.)
I found my named character under "documents>DayZ" but nothing pertaining to a profile under appData>local.
I would rather clear so I cant just use admin tools but if I can set a profile for my client, I have no Idea how to do, that would be good.

**Comment by HotNachos** [comment]
Fixed it. But binded key for Admin menu Isn't working.

Server File under "D:\Program Files (x86)\Steam\steamapps\common\DayZServer\ServerProfile_1\VPPAdminTools\Permissions\SuperAdmins"

has superadmin.txt as "76561198000832659" in line 1

My server run.bat line is as follows.
-config=serverDZ.cfg -port=2302 " -mod=@CF;@VPPNotifications;@VPPAdminTools" -profiles=ServerProfile_1 -dologs -adminlog -netlog

**Comment by GravityWolfNotAmused** [comment]
Do you have the default folders for the tools? We don't just put superadmins.txt inside of the root profiles folder.

**Comment by GravityWolfNotAmused** [comment]
If you don't then they are in our discord under #helpful-content

**Comment by HotNachos** [comment]
Sorry if I’m being annoying. I followed github direction and steam directions exact. I don’t know what you mean by “ Do you have the default folders for the tools? We don't just put superadmins.txt inside of the root profiles folder“. The only folder that has super admin.text is under the folder created by server start. I’ll check discord when I get home for helpful-content and love help if anybody’s there.

**Comment by HotNachos** [comment]
running it now
got it all working
On first setup I must have done something wrong because I did a clean wipe and reinstall now my binds work with no access violations
