### ISSUE TITLE
MOD wont install!

### ISSUE THREAD

**Issue by TheArtfulBadger** [VanillaPlusPlus/VPP-Admin-Tools#22]
Followed all the steps, to be greated by this when i tried to load the sever? 

You were kicked off the game. (file not found: @VPPNotifications\addons\vppnotifications.pbo)

How would i fix this?

**Comment by Da0ne** [comment]
Make sure you have the dependency mods installed on the server and client. You seem to be missing VPPNotifications from your client is what the kick message states.
[Link](https://steamcommunity.com/sharedfiles/filedetails/?id=1680673106)

The mod load order on the server is also important: -mod=@CF;@VPPNotifications;@VPPAdminTools

**Comment by TheArtfulBadger** [comment]
How do i install the mods to the client? As i dont see anywhere for mods?

**Comment by TheArtfulBadger** [comment]
Sorry forgot to mention i do have the VPPNotifications already installed

**Comment by Da0ne** [comment]
You either use the official DayZ launcher or get DZSA Launcher.

**Comment by TheArtfulBadger** [comment]
Nope i did that, every installed step by step in the correctorder, but now its just loading up the game and telling me straight away "connection lost"?

**Comment by GravityWolfNotAmused** [comment]
Let me see your start up command line for the server please.

**Comment by TheArtfulBadger** [comment]
![20191210_084409](https://user-images.githubusercontent.com/58713862/70513599-e2266e80-1b29-11ea-84e6-fa8ba042401c.jpg)

**Comment by Da0ne** [comment]
Remove `mod=` i don't think thats needed. Read the instructions on your server provider control panel

**Comment by TheArtfulBadger** [comment]
Ok i'll give it ago.

Thats half the problem i click the more information buttons or help/description and the page it gives me is all in German. 

Can i check the filezilla?
Ive moved the files to the root. Ive moved keys 
separately to keys tho the 2 VPP MODS both have the same key file yeah? 

![20191210_101026](https://user-images.githubusercontent.com/58713862/70520502-8f52b400-1b35-11ea-8af4-6e7933008698.jpg)

Is that right, ive git a feeling if ive gone wrong its prob going to be here?

Again this must be annoying, but i do appreciate the help.

**Comment by Da0ne** [comment]
Yes they all share the same key.
I recommend you translate that and follow the instructions. just dropping the files in with FTP wont work as it needs to be added to the startup params of the server executable.

**Comment by TheArtfulBadger** [comment]
Ok cool, i will get on that. But as far as the filezilla side of things, is that right? Know ive just got to sort it out on the main notrado server page?

**Comment by Da0ne** [comment]
When you move over the mods, thats all good yea. BUT in the control panel you need to make sure you update the mods you want to run. I recommend if you can get a server from [Vilayer](https://www.vilayer.com/) they have an auto installer for mods. You can browse what you wish to install and everything is automated apart from configuration related to the mod itself (like adding your steam64 for our tools) 
![image](https://user-images.githubusercontent.com/38754008/70523291-d624c600-1b96-11ea-96e6-0f2fd520d415.png)

**Comment by GoofyGame** [comment]
I have the same problem.
You were kicked off the game. (file not found: @VPPNotifications \ addons \ vppnotifications.pbo)

Server and client of the latest revision, (cracked)
I did not quite understand the installation of mods.
In the server bat file: -mod = mods\@CF; mods\@VPPNotifications; mods\@vppadmintools
The same thing in the client bat file.
The keys are in folders.
Tell me step by step instructions.

**Comment by Da0ne** [comment]
Server and client of the latest revision, (cracked)?
What is cracked? can you show me

**Comment by GoofyGame** [comment]
Cracked with SmartSteamLoader_x64

**Comment by Da0ne** [comment]
Link me to where you got this client from.

**Comment by GoofyGame** [comment]
Client and server download from steam,  then  i use SmartSteamLoader_x64, to launch without steam.
Sorry my poor english.
I need detailed installation instructions for these three mods.

**Comment by Da0ne** [comment]
Im not gonna help you install my mods on illegal operated software.
Sorry, remove our mods or purchase and play the game legitimately.
