### ISSUE TITLE
Some minor, but anoying bugs

### ISSUE THREAD

**Issue by LBmaster001** [VanillaPlusPlus/VPP-Admin-Tools#23]
Hey,
First of all, I'm realy impressed by your work, but there are some issues I would like to have fixes.
1. If you scan the Map for Items, all Items that have the scanned one as a parent, will appear too, which makes it realy confusing, if you get 26 M4s displayed, but there any only ~12 around. please change `if (GetGame().ObjectIsKindOf(obj,data.param1) && !FoundItems.Contains(obj))` in the XMLEditor.c to something like `string objtype = obj.GetType ();
objtype.ToLower();
if (objtype== data.param1 && !FoundItems.Contains(obj))`
or at least change `ItemPositons.Insert(data.param1 +"_"+ i.ToString(),obj.GetPosition());` to `ItemPositons.Insert(obj.GetType() +"_"+ i.ToString(),obj.GetPosition());` to make it clear, that the Item is from a different type

2. If you scanned the map for an item and you get the items displayed on the items displayed on the map and press escape, the Map will stay opened

3. Pressing "Restart Server" in the Server Manager crashes the Server

4. If you are in the Free cam and you go into a Menu like the "esc" Menu, moving the mouse around still causes the Camera to move

**Comment by GravityWolfNotAmused** [comment]
I'm sorry for the late response; however, I'm in the process of removing CF from the tools and preparing for a large update. I will investigate these bugs and hopefully solve them all. This ticket will remain open.
