### ISSUE TITLE
Always Raining in Chernorus when I'm (admin) is in game

### ISSUE THREAD

**Issue by MarvinFS** [VanillaPlusPlus/VPP-Admin-Tools#25]
Colleagues,

One question, in your mod default WeatherSettingsPresets.json is empty
So when I connect to the server (as I'm set as super user) it probably resets weather system to VPPadmin mod preset and it's like always raining... How to override that or what settings should I put to json so It would respect game weather settings?

![image](https://user-images.githubusercontent.com/7998636/71786791-9fc15600-3031-11ea-8c70-5ba471e378b8.png)

**Comment by GravityWolfNotAmused** [comment]
You'd have to set the weather through your init.c
