### ISSUE TITLE
Player issue

### ISSUE THREAD

**Issue by HaliteZOD** [VanillaPlusPlus/VPP-Admin-Tools#28]
Selecting a player in player manager and "healing or godmode" or anything will set them as the admin name and all commands after will affect them even when they are not checked. Having admin and player relog fixes this

**Comment by Da0ne** [comment]
Can you please explain this further more? I don't understand what you mean by "admin name"

**Comment by HaliteZOD** [comment]
Their name on the server changes, To my name. and all actions that would affect me affects them instead.

**Comment by Da0ne** [comment]
Thanks for the report, i will look into the issue.
