### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by SystemAnonymous** [VanillaPlusPlus/VPP-Admin-Tools#29]
Hello. 

I am trying to install this admin tool. I have followed the instructions on github. 
I have added myself into the SuperAdmin.txt But when i'm in the server and press Insert. I do not get any menu pop up. But when I press backspace It takes me into a weird floating camera mode.. lol

Any ideas how to fix this please?

Thank you
Kind Regards

**Comment by Da0ne** [comment]
Check your keybinds. DayZ settings ingame.
