### ISSUE TITLE
Player Unknown (105305909) kicked from server: 6 (Client contains PBO which is not part of server data: D:\Steam\steamapps\common\DayZ\!Workshop\@VPPAdminTools\addons\vppadmintools.pbo)

### ISSUE THREAD

**Issue by jeffreyf200** [VanillaPlusPlus/VPP-Admin-Tools#30]
I followed the installation process carefully but after I activated the mod this error message (Player Unknown (105305909) kicked from server: 6 (Client contains PBO which is not part of server data: D:\Steam\steamapps\common\DayZ\!Workshop\@VPPAdminTools\addons\vppadmintools.pbo)) showed in my server console when I was trying to enter the server and thus cannot enter the server. When I disabled this mod, I can enter the server again.  I tried some other mods and I can run them without a problem. Any advice on how to deal with this problem?

**Comment by Da0ne** [comment]
Make sure you have the mod keys in the Keys folder. If you are using a GSP ( Game service Provider ) then double check Keys folder using FTP. Other than that, make sure your client is actually loading the mod before you connect.
