### ISSUE TITLE
SERVER: Can't compile "World" script module!

### ISSUE THREAD

**Issue by ThatOneGuy35** [VanillaPlusPlus/VPP-Admin-Tools#31]
VPPAdminTools/4_world/plugins\permissionmanager\permissionmanager.c(8): Multilple declaration of class 'PermissionManager'

Server OS: Windows 10
Using omega launcher to launch server and manage mods.

**Comment by GravityWolfNotAmused** [comment]
You are running cot, and vpp. Pick one, friend.
