### ISSUE TITLE
VPPAdminTools file is too  big for the Nitrado server (Dayz)?

### ISSUE THREAD

**Issue by RandomPlayer1999** [VanillaPlusPlus/VPP-Admin-Tools#32]
I am trying to instal the VPPAdminTools for my Dayz server, but it appears the Addon .pbo file is too big. I tried to log in into the server, but the game keeps giving me the error that there is no PBO file detected (because, I suspect, the server isn't uploading the file?) Can someone help me with this?

Edit: It's a Nitrado server for 4 people.
![image](https://user-images.githubusercontent.com/62068748/76435576-73221580-63b7-11ea-9e0b-0759126eda47.png)

**Comment by GravityWolfNotAmused** [comment]
Use an FTP software like filezilla, or winscp. Never use the web file browser to upload mods.

**Comment by RandomPlayer1999** [comment]
In fact, that is the only way of uploading the mod. So yes, I have used
Winscp to upload the three mod files, but the .pbo file that is greyed out
in the screenshot is for some reason too big for the server.
The error message I get in the game is as follows:
[image: image.png]
Sadly, you already closed the thread, so I send this e-mail directly to you.
Could it be something else?

Op wo 11 mrt. 2020 om 19:29 schreef Larry <notifications@github.com>:

**Comment by GravityWolfNotAmused** [comment]
There are mods that are way bigger than VPP, so idk if space has anything to do with it. Try specifically uploading the pbo to the correct location?

**Comment by RandomPlayer1999** [comment]
I've tried to reuploqd the file itself true Winscp, but it is still gray
after reupload, with no results.


Op wo 11 mrt. 2020 om 21:11 schreef Larry <notifications@github.com>:

**Comment by GravityWolfNotAmused** [comment]
Question, you are hosting a PC server correct?

**Comment by GravityWolfNotAmused** [comment]
Or are you hosting a console (PS4/Xbox) server?

**Comment by RandomPlayer1999** [comment]
Yes, I am hosting a Pc server
Currently, I am trying to add the .pbo and .bisign files to the steamapps
location locally


Op wo 11 mrt. 2020 om 21:43 schreef Larry <notifications@github.com>:

**Comment by GravityWolfNotAmused** [comment]
Can you send me a photo of your command line arguments for -mod?

**Comment by RandomPlayer1999** [comment]
[image: image.png]

I am currently able to enter the server. The mod appears to work, only
nothing of my key bindings work. I suppose thats the next problem to solve.

Op wo 11 mrt. 2020 om 21:48 schreef Larry <notifications@github.com>:

**Comment by GravityWolfNotAmused** [comment]
I have not gotten a start up command line. You aren't uploading them.
