### ISSUE TITLE
Webhook Customization

### ISSUE THREAD

**Issue by AaronMickDee** [VanillaPlusPlus/VPP-Admin-Tools#34]
Is there plans to allow further customization of webhook messages? Maybe a way to edit the JSON file template?

**Comment by Da0ne** [comment]
Currently no, however you can view the source code and create a mod that is dependent on the admin tools. With that you can override and append your changes. The Steamworkshop mod dependency system is inplace. Modding experience with DayZ + scripting is required to accomplish this.
