### ISSUE TITLE
Server Wont start, When I install VPP Map, VPP Admin Tools and Notification. 

### ISSUE THREAD

**Issue by Richfie21** [VanillaPlusPlus/VPP-Admin-Tools#35]
Our server wont start, and I noticed they have same keys, what should I do? Rename it or just VPP.bikey or generate Keys each mods?

**Comment by GravityWolfNotAmused** [comment]
They are all the same key, that's why they all have the same name. Just use one no need to change anything.

**Comment by Richfie21** [comment]
I did that only VPP.bikey on Key folder, but still the server wont Restart already added also on parameters

**Comment by GravityWolfNotAmused** [comment]
what is your start up command line?

**Comment by Richfie21** [comment]
verifysignature = 1

**Comment by Richfie21** [comment]
@Manifestation\@A;@Manifestation\@Airdrop;@Manifestation\@Atv_mung;@Manifestation\@AutoRun;@Manifestation\@Banking;@Manifestation\@Base Furniture Mods 2.0;@Manifestation\@BaseBuildingLogs;@Manifestation\@BaseBuildingPlus;@Manifestation\@BetterSuppressors;@Manifestation\@Breachingcharge;@Manifestation\@BuildAnywhere;@Manifestation\BuilderItems;@Manifestation\@CF;@Manifestation\CheckPulse;@Manifestation\@CJ187-Cars;@Manifestation\@Cl0uds Military Gear;@Manifestation\@Code Lock;@Manifestation\@Community-Online-Tools;@Manifestation\@DayZ-Expansion-Chat;@Manifestation\@DayZ-Expansion-Notifications;@Manifestation\@DisablePlot;@Manifestation\@Ear-Plugs;@Manifestation\@FIDOv PACK 4;@Manifestation\@FS;@Manifestation\@GoreZ;@Manifestation\@Kamaz_Truck;@Manifestation\@KillFeed;@Manifestation\@LoadingScreen;@Manifestation\@MassManyItemOverhaul;@Manifestation\@MoreDoors;@Manifestation\@MosinScope;@Manifestation\@mrap;@Manifestation\@MunghardsItempack;@Manifestation\@PartyLayout;@Manifestation\@PartyMe;@Manifestation\@StreetLighting;@Manifestation\@TimeDestruction;@Manifestation\@Trader;@Manifestation\@ToxicZone;@Manifestation\@Unlimited Stamina;@Manifestation\@Updated_No_Vehicle_Damage;@Manifestation\@VanillaPlusPlusMap;@Manifestation\@VehicleActivityLogs;@Manifestation\@Zeroy-FishingZ;@Manifestation\@ZomBerry Admin Tools

**Comment by Da0ne** [comment]
You are probably missing CF mod. Make sure the order of your mods follows as this; 

> @CF,@VPPNotifications;@VPPAdminTools;@VanillaPlusPlusMap;@OtherModsIfAny

**Comment by Richfie21** [comment]
I have CF maybe the order I'll try that

**Comment by GravityWolfNotAmused** [comment]
Still having issues?

**Comment by Richfie21** [comment]
@Manifestation\@CF;@Manifestation\@VPPNotifications;@Manifestation\@VPPAdminTools;@Manifestation\@VanillaPlusPlusMap;@Manifestation\@A;@Manifestation\@Airdrop;@Manifestation\@Atv_mung;@Manifestation\@AutoRun;@Manifestation\@Banking;@Manifestation\@Base Furniture Mods 2.0;@Manifestation\@BaseBuildingLogs;@Manifestation\@BaseBuildingPlus;@Manifestation\@BetterSuppressors;@Manifestation\@Breachingcharge;@Manifestation\@BuildAnywhere;@Manifestation\BuilderItems;@Manifestation\CheckPulse;@Manifestation\@CJ187-Cars;@Manifestation\@Cl0uds Military Gear;@Manifestation\@Code Lock;@Manifestation\@Community-Online-Tools;@Manifestation\@DayZ-Expansion-Chat;@Manifestation\@DayZ-Expansion-Notifications;@Manifestation\@DisablePlot;@Manifestation\@Ear-Plugs;@Manifestation\@FIDOv PACK 4;@Manifestation\@FS;@Manifestation\@GoreZ;@Manifestation\@Kamaz_Truck;@Manifestation\@KillFeed;@Manifestation\@LoadingScreen;@Manifestation\@MassManyItemOverhaul;@Manifestation\@MoreDoors;@Manifestation\@MosinScope;@Manifestation\@mrap;@Manifestation\@MunghardsItempack;@Manifestation\@PartyLayout;@Manifestation\@PartyMe;@Manifestation\@StreetLighting;@Manifestation\@TimeDestruction;@Manifestation\@Trader;@Manifestation\@ToxicZone;@Manifestation\@Unlimited Stamina;@Manifestation\@Updated_No_Vehicle_Damage;@Manifestation\@VehicleActivityLogs;@Manifestation\@Zeroy-FishingZ

**Comment by Richfie21** [comment]
the above wont work

but when I start it only with this:

@manifestation@CF;@manifestation@VPPNotifications;@manifestation@VPPAdminTools;@manifestation@VanillaPlusPlusMap

it works

**Comment by Richfie21** [comment]
is it conflict with Community Online Tools?

**Comment by Richfie21** [comment]
Yes I resolved it the conflict is 'Community Online Tools'
Thanks for the help :D
