### ISSUE TITLE
Free camera problems

### ISSUE THREAD

**Issue by EvGeNu4** [VanillaPlusPlus/VPP-Admin-Tools#39]
If you are in a free camera and throw a grenade, the game crashes!

**Comment by GravityWolfNotAmused** [comment]
Please refrain from doing this, it will be fixed next patch. Thanks for the report! <3

**Comment by EvGeNu4** [comment]
In the vpp patch? or a game patch?

**Comment by EvGeNu4** [comment]
> Please refrain from doing this, it will be fixed next patch. Thanks for the report! <3

In the vpp patch? or a game patch?

**Comment by GravityWolfNotAmused** [comment]
VPP patch, I am keeping bugs open, so I can see them as I work.

**Comment by EvGeNu4** [comment]
> VPP patch, I am keeping bugs open, so I can see them as I work.

Tell me please. When will this patch be released?

**Comment by GravityWolfNotAmused** [comment]
There are a bunch of things that need to be refactored, and/or worked on. I cannot give a specific, just please refrain from having a grenade in your hand when using free cam for the time being. I will update this ticket when the fix is pushed.
