### ISSUE TITLE
Game crashing, vehicle disappearing, items with 0 use, bugged tents

### ISSUE THREAD

**Issue by Salgijash** [VanillaPlusPlus/VPP-Admin-Tools#40]
Found a couple of bugs:
1. Game crashes when I scroll through weapon list.
2. Vehicle that I spawn on my private server disappear after logging out.
3. Spawned items like sewing kits, engine oil, ducktape - have 0 uses in them (bar under them is empty)
4. Spawned tents (large and car tents) cannot be deployed - it says to choose location for set-up but nowhere does the tent is able to be deployed.

**Comment by GravityWolfNotAmused** [comment]
1: Turn Item preview off, some items packaged by BI are unfinished.
2: That has to be an issue with your lifetime.
3: idk?
4: We don't touch anything with tents, so it must be another mod you are using.
