### ISSUE TITLE
assets show up in ItemManager dialog

### ISSUE THREAD

**Issue by sgoudelis** [VanillaPlusPlus/VPP-Admin-Tools#42]
Hello.

I have a server and after the DayZ Expansion installation, I see that there is a large number of static assets in the list available to spawn in the ItemsManager when they should have being available in the ObjectManager dialog (which they are not). 

More specifically, there is a mod called BuilderItems which makes  hundreds of static assets available to the ObjectManager. Now, in my installation I see all those items in the ItemsManager which is problematic. 

I understand that this is probably not your issue, but some help would be appreciated. 

Thank you

**Comment by GravityWolfNotAmused** [comment]
This is something that the creator of Builder Items has changed, please contact NotABanana to discuss your issue with item scope as I cannot change his mod, and we simply just load the proper scope for scene objects and items.
