### ISSUE TITLE
1.08 Update Issue

### ISSUE THREAD

**Issue by DexterTheGod** [VanillaPlusPlus/VPP-Admin-Tools#43]
Okay so we have been using VPP since before the 1.08 update but after the update we have ran into some issues. It is on the server and everything seems to be working properly except the teleporting. When staff teleport through either keybind, player manager, or teleport map it crashes their game. Some get a few teleports in but eventually they crash.

**Comment by GravityWolfNotAmused** [comment]
Does anyone have a crash report? Please provide any crash report from the server and clients who are crashing please.

**Comment by DexterTheGod** [comment]
Will do, give me a second

**Comment by DexterTheGod** [comment]
[script_2020-06-30_16-29-39.log](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/4854263/script_2020-06-30_16-29-39.log)
[crash_2020-06-30_16-29-39.log](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/4854264/crash_2020-06-30_16-29-39.log)

**Comment by DexterTheGod** [comment]
Only the client is crashing

**Comment by GravityWolfNotAmused** [comment]
```
------------------------------------
PANZER, 30.06 2020 16:30:14
NULL pointer to instance
Class:      'ExpansionChatHandler'
Function: 'UpdateScroller'
Stack trace:
DayZExpansion/Scripts/5_Mission/dayzexpansion\gui\chat\expansionchathandler.c:94
DayZExpansion/Scripts/5_Mission/dayzexpansion\gui\chat\expansionchat.c:245
DayZExpansion/Scripts/5_Mission/dayzexpansion\gui\chat\expansionchat.c:89
scripts/5_Mission/mission\missiongameplay.c:105
JM/CF/Scripts/5_Mission/communityframework\mission\missiongameplay.c:16
JM/COT/Scripts/5_Mission/communityonlinetools\missiongameplay.c:44
TM/Trader/scripts/5_Mission/mission\missiongameplay.c:11
DayZExpansion/Scripts/5_Mission/dayzexpansion\mission\missiongameplay.c:312
Scope/Scripts/5_Mission/lol.c:6

------------------------------------
PANZER, 30.06 2020 16:30:27
NULL pointer to instance
Class:      'ExpansionWorldMappingModule'
Function: 'LoadFile'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\classes\systems\mapping\expansionworldmappingmodule.c:380
DayZExpansion/Scripts/4_World/dayzexpansion\classes\systems\mapping\expansionworldmappingmodule.c:216
DayZExpansion/Scripts/4_World/dayzexpansion\classes\systems\mapping\expansionworldmappingmodule.c:159
scripts/3_Game/dayzgame.c:2333
```

This seems to be completely Expansion related, friend.

**Comment by DexterTheGod** [comment]
Can anything be done to prevent crashing? Since it strictly only happens when you teleport with VPP Admin Tools, Never happened before 1.08

**Comment by DexterTheGod** [comment]
Or will I have to reach out to Expansion devs?

**Comment by GravityWolfNotAmused** [comment]
You'll have to reach out to them as I do not have the ability to fix these issues since I do not maintain that mod.

**Comment by DexterTheGod** [comment]
Thank you for the help
