### ISSUE TITLE
Missing description on all buttons

### ISSUE THREAD

**Issue by Blefino** [VanillaPlusPlus/VPP-Admin-Tools#46]
[https://ctrlv.cz/M2m1](url) please check picture on the link, it is not possible to use this mode anymore when everything is without description

**Comment by GravityWolfNotAmused** [comment]
Excuse me can you explain what you mean by this?

**Comment by GravityWolfNotAmused** [comment]
Also, your photo doesn't function for me, so I'm clueless what you are talking about

**Comment by Blefino** [comment]
I will try to send it via this answer😊  Odesláno z aplikace Pošta pro Windows 10 Od: LarryOdesláno:pátek 17. července 2020 23:16Komu: VanillaPlusPlus/VPP-Admin-ToolsKopie: Blefino; AuthorPředmět: Re: [VanillaPlusPlus/VPP-Admin-Tools] Missing description on all buttons (#46) Also, your photo doesn't function for me, so I'm clueless what you are talking about—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GravityWolfNotAmused** [comment]
...?

**Comment by Blefino** [comment]
do you have some link where I can upload screen?

**Comment by Blefino** [comment]
![VPP](https://user-images.githubusercontent.com/68446575/87832001-372b1f80-c885-11ea-9caa-2bb320ed27b9.JPG)

**Comment by Blefino** [comment]
all buttons in all "options" like spawner, weather, builder and so on, looks like this. I have to go sleep, if you will need some more information I will send it tomorrow.

**Comment by GravityWolfNotAmused** [comment]
Are you using a different language?

**Comment by Blefino** [comment]
Morning, yes, I have DayZ in Czech language.

**Comment by GravityWolfNotAmused** [comment]
@Blefino Currently, we don't have a translation for the Czech language; however, if you have a good understanding of both English and Czech I ask that you help us out and translate our mod to better help those who only understand the Czech language. If by chance you cannot help out, we will add the English translation to the Czech translation, so it isn't left blank.

**Comment by GravityWolfNotAmused** [comment]
Please contact Mark through our Discord stating you wish to translate for us, or not so we may fix it ASAP.

**Comment by Blefino** [comment]
@GravityWolfNotAmused I have tried to change the language to English and it doesn't help. I think I can help with translation.
