### ISSUE TITLE
VPP webhooks

### ISSUE THREAD

**Issue by STA-BOND7** [VanillaPlusPlus/VPP-Admin-Tools#51]
SO i have had no issue with the mod until I added Expansion! after I did the webhooks that were working .. no longer work. if you have any ideas  let me know!

**Comment by GravityWolfNotAmused** [comment]
Can I please have your webhook address?

**Comment by STA-BOND7** [comment]
I apologise.  I found the issues.   VPP needs to be the last mod in the
list for the launch perams.

Confirmed working.

**Comment by GravityWolfNotAmused** [comment]
Understood, have a great day!
