### ISSUE TITLE
Its me again LOL    retard on a stick     cant change keybinds after update

### ISSUE THREAD

**Issue by STA-BOND7** [VanillaPlusPlus/VPP-Admin-Tools#52]
![20201119133342_1](https://user-images.githubusercontent.com/74379042/99727403-c3846380-2a6c-11eb-98f2-dbf583ff0268.jpg)

as shown there is no list for changing keybindings... but other then that i have no issues at all!!!!

**Comment by GravityWolfNotAmused** [comment]
I'm almost off of work, and will be investigating it.

**Comment by GravityWolfNotAmused** [comment]
This was resolved.
