### ISSUE TITLE
[FEATURE REQUEST] Be able to despawn all of a certain item type.

### ISSUE THREAD

**Issue by idgas01** [VanillaPlusPlus/VPP-Admin-Tools#55]
I recently installed a mod that lets me lock vehicles.  Because I did not have any admin tools, I just added the key item to my types.xml and I spawned 1,000 of those keys in the server.  But now I want to delete all keys in the server without doing a server wipe.  I asked about this on the Workshop page and I was told "Good suggestion for a feature."  So i cam here and decided to create a ticket for the feature request.  I was also told "You would need to write some script to run in your mission."  If I knew how to script, I would do that, but I don't even know where to begin.  If I had the ability, I don't mind doing the work.  But I don't have the ability, so what can I do?  So hopefully you will considering adding this feature.  I don't know if setting lifetime to 1 will work.  Someone told me not to do that and to see if VPPTools or COT would do it instead.  I don't get why.  Why would setting lifetime to 1 and nominal and min to 0 not be a good way to make it work?  But I'm new to DayZ, setting up servers and mods, so maybe they are right.

**Comment by GravityWolfNotAmused** [comment]
Hello @idgas01,

The one reason I will not add a feature to delete all of the items off of your server and package it into VPP is due to the time it takes to get all items and delete them would halt your server, and freeze every player.

Sorry.
