### ISSUE TITLE
Admin menu won't open

### ISSUE THREAD

**Issue by azynkron** [VanillaPlusPlus/VPP-Admin-Tools#6]
(Using DayZ 1.03)
I can't get the admin menu to open.

- Added myself in the superadmin.txt (Steam 64 ID)
- Mod is added to client via DayZ launcher
- Mod is added to server and included in command line options
- Bikeys are copied e t c. 
- I login as admin (#login XXXX which works)
- I set the key with Insert (even tried to change it) 
- I press the key to open the Admin menu

Nothing happens. Is there a debug log somewhere so I can see where it goes wrong?
I'm experimenting on a LAN server right now if that matters.

**Comment by azynkron** [comment]
I guess this tool is dead. Uninstalling.

**Comment by GravityWolfNotAmused** [comment]
First off, it's 630 am for me. For second, if you don't see it your formatting could be wrong. What's your superadmins.txt look like?

**Comment by azynkron** [comment]
It's been 06:30 for two days? What time zone do you live in?
________________________________

**Comment by Da0ne** [comment]
Make sure the steam64 id actually leads to your profile.
Make sure you placed your id in the EXACT same way as we have the default generated IDs
![image](https://user-images.githubusercontent.com/38754008/60197051-f4656680-9881-11e9-8228-bdd8a7753c24.png)
with NO spaces after the ID or between the ` |` and the rest of the ID
Once you run the server, check the logs in your server profile. scripts_%timestamp% and look if your ID is there, if it is then you have successfully done the most simple thing in the world. :)

**Comment by azynkron** [comment]
Well, that was the first thing I checked.. for typos. I've run Arma servers for years so I'm aware
of how sensitive they are and how easy it is to miss a single line.

The logs say
SCRIPT       : Adding SuperAdmin: BadTrip GUID: 76561197994947226 To the SuperAdmin List!

So, that part works but the menu isn't. Anyway.. Thanks for the reply.
________________________________

**Comment by GravityWolfNotAmused** [comment]
What's your client start up command line?

**Comment by kbiernat** [comment]
I'm having the same issue, and I'd really like to fix it.
This appears for my ID in logs
```
16:7:41 | [PermissionManager] Adding Super Admin (765611988076xxxxx)
...
18:11:6 | Player "xxxx" (steamId=765611988076xxxxx) connected to server!
```
and in the scripts log I get this
```
SCRIPT       : string log =  '2022/11/5 |  [VPPAdminTools] Player 765611988076xxxxx attempted login, and failed! Total Attempts: 2'
SCRIPT       : string log =  '2022/11/5 |  [VPPAdminTools] Player 765611988076xxxxx attempted login, and failed! Total Attempts: 3'
```
Running in Nitrado, startup command is
```
== C:\SERVICES\*********_SHARE\ftproot\dayzstandalone\DayZServer_x64.exe
== "C:\SERVICES\*********_SHARE\ftproot\dayzstandalone\DayZServer_x64.exe" -ip=*********.24 -port=********* -cpuCount=4 -limitFPS=100 -adminlog -config=serverDZ.cfg "-mod=@CF;@Community-Online-Tools;@Dabs-Framework;@VPPAdminTools;*******************;@WindstridesClothingPack" -profiles=C:\SERVICES\************_SHARE\ftproot\dayzstandalone/config -BEPath=C:\SERVICES\*****************_SHARE\ftproot\dayzstandalone\battleye -noFilePatching -dologs -VMErrorMode "log_only" -freezecheck
```

**Comment by AndreiCoshare** [comment]
Ran into same issue, noticed after troubleshooting that I had the wrong Steam ID provided from a site... I used https://steamid.io/ instead and it gave me the right Steam ID. I noticed this in the logs when I joined the server my ID was not the same as the one I put in the Superadmins.txt file, maybe that can help others.
