### ISSUE TITLE
[BUG] Item Previews have a high z-index and will appear on top of other windows.

### ISSUE THREAD

**Issue by idgas01** [VanillaPlusPlus/VPP-Admin-Tools#60]
![DayZ_x64_z9fSmdQhbu](https://user-images.githubusercontent.com/75463665/104107686-ecaebc80-5283-11eb-8079-0e3e2fd71512.png)

**Comment by GravityWolfNotAmused** [comment]
Hello @idgas01, That's something DayZ does natively. There is no way to my knowledge to lower it.
