### ISSUE TITLE
Vehicle spawn

### ISSUE THREAD

**Issue by ironeyex** [VanillaPlusPlus/VPP-Admin-Tools#61]
Hi,
Firstly great work, your tool is by far the easiest to use.

The issue I face is when an admin spawns a pre-set vehicle it will despawn without warning, the timing of despawn is hard to pinpoint. Is this a bug or can you point me to where the lifetime of manually spawned vehicles would be? 
Player purchased vehicles are fine.

Thanks

**Comment by Da0ne** [comment]
Hello, thanks!

You need to increase the lifetime of the vehicle types within your CLE (Central Loot Economy) configuration XMLs. Found in your mission, check **types.xml** for the class names of vehicles. **Lifetime** value is in seconds, increase it and it will resolve the issue.

**Comment by ironeyex** [comment]
Hi Da0ne! 

Thank you for the detailed response. I have found and adjusted the vanila vehicles. Do you know where I would find the same lifetime setting for the dingo and psyco mod vehicles?

Thanks

**Comment by Da0ne** [comment]
I suggest you contact the author of the mod.

Thanks.

**Comment by ironeyex** [comment]
ok will do thanks for your help!
