### ISSUE TITLE
Possible Weather Manager Glitch

### ISSUE THREAD

**Issue by theexistencerp** [VanillaPlusPlus/VPP-Admin-Tools#62]
I believe the weather manager has messed up the weather on my server. I can provide my init.c but here's the situation. It constantly rained on the server a couple months ago. Now, it doesn't rain at all. I tried to manually make it rain in the weather manager and it will rain, but it just goes from 1-100 and I don't know how to set it up properly. I want to think it's conflicting with the init.c but obviously you all will know best. I just need my weather to work how I want it and it's not. Thanks!

**Comment by GravityWolfNotAmused** [comment]
The weather manager doesn't control the change of weather, it just allows you to set the weather. The weather controller built into the game will change the weather as time passes. Right now it will set all 4 values, and I will change that in the future; however, it doesn't control how the server changes it as time passes.

**Comment by theexistencerp** [comment]
I get that, but I can't figure out any reason why my init.c wouldn't be controlling my weather properly... This may be more in depth than I am thinking. Do you have any ideas at all for me?

**Comment by GravityWolfNotAmused** [comment]
![image](https://user-images.githubusercontent.com/24533882/105447661-dadcfa00-5c31-11eb-8191-1918249eefd6.png)
What does your weather section look like?

**Comment by theexistencerp** [comment]
`//INIT WEATHER BEFORE ECONOMY INIT------------------------
	Weather weather = g_Game.GetWeather();
    weather.MissionWeather(true);    // false = use weather controller from Weather.c
    weather.GetOvercast().SetLimits(0.0, 0.7);
    weather.GetRain().SetLimits(0.0, 1.0);
    weather.GetFog().SetLimits(0.0, 0.5);

    weather.GetOvercast().SetForecastChangeLimits(0.0, 0.8);
    weather.GetRain().SetForecastChangeLimits(0.0, 1.0);
    weather.GetFog().SetForecastChangeLimits(0.0, 0.45);

    weather.GetOvercast().SetForecastTimeLimits(100, 700);
    weather.GetRain().SetForecastTimeLimits(200, 500);
    weather.GetFog().SetForecastTimeLimits(100, 1200);

    weather.GetOvercast().Set(Math.RandomFloatInclusive(0.5, 1.0), 0, 0);
    weather.GetRain().Set(Math.RandomFloatInclusive(0.0, 0.2), 0, 0);
    weather.GetFog().Set(Math.RandomFloatInclusive(0.0, 0.1), 0, 0);

    weather.SetWindMaximumSpeed(40);
    weather.SetWindFunctionParams(15, 25, 50);`

**Comment by theexistencerp** [comment]
![image](https://user-images.githubusercontent.com/77822339/105447892-c6512f80-5c3a-11eb-9dd8-557296ad9b68.png)

**Comment by theexistencerp** [comment]
I recently changed it to this because of a recommendation from someone.

**Comment by GravityWolfNotAmused** [comment]
why are you using true for MissionWeather?

**Comment by theexistencerp** [comment]
No clue.

**Comment by theexistencerp** [comment]
I copied and pasted. If that is true, I thought it meant it read the following settings. What does it actually do?

**Comment by GravityWolfNotAmused** [comment]
// false = use weather controller from Weather.c

**Comment by theexistencerp** [comment]
I see that, but so what you are saying is I change that to false, then I have to go into weather.c? It wouldn't use any of the settings in the init.c. Why should I do that

**Comment by GravityWolfNotAmused** [comment]
What makes you believe that it wouldn't change anything?

bool GetMissionWeather(); is a function that determines if OnBeforeChange event triggers WorldDatas WeatherOnBeforeChange function. If you have this set to true, this function doesn't do anything, WeatherOnBeforeChange never gets called, so this leave in the question. What controls the weather when the controller is disabled. Where is your calculation for weather change coming from then? What triggers the next change in the weather? I am really curious to what you understand MissionWeather and what it controls because the only place that it's mentioned is OnBeforeChange, and nowhere else.

https://github.com/Thurston00/DayZSAEnfScript/blob/c765b665b52befff08660c6153883e676f0e64c3/scripts/4_World/Classes/Worlds/ChernarusPlus.c#L44

https://github.com/Thurston00/DayZSAEnfScript/blob/c765b665b52befff08660c6153883e676f0e64c3/scripts/3_Game/Weather.c#L115

**Comment by theexistencerp** [comment]
So are you saying I need it to be false? I honestly don't know what all this means as I am fairly new to it and still learning. Once I messed with the VPP Weather Manager, I now can't get rain to stop on my server. So I assume change it to false?

**Comment by GravityWolfNotAmused** [comment]
The defaults state that false means use the internal weather controller, unless you have another weather control like Namalsks, use false.

https://github.com/BohemiaInteractive/DayZ-Central-Economy/blob/d468c186d763292f11266938111ce50c30a5e561/dayzOffline.chernarusplus/init.c#L6
