### ISSUE TITLE
Many incompatible mods

### ISSUE THREAD

**Issue by Marshmalllow09** [VanillaPlusPlus/VPP-Admin-Tools#63]
So first off, I started up a Namalsk server, with vppa, and everything worked fine. But Namalsk is very very boring to me so I switched too Expansion cherno. Now when I run some of the same mods, the server doesn't start. A really big one being Trader.

**Comment by GravityWolfNotAmused** [comment]
So, where do I start, for the last months the whole community and yourself have been complaining about compatibility with other mods. I have, along with other community modders, tested this issue extensively and even spent my whole birthday last year on this issue as well. Bohemia has fixed this issue. It's in the EXP build of the game, BI said release is scheduled on 2/16 on their [Twitter](https://twitter.com/DayZ/status/1355218658629464067?s=20), that is if QA doesn't kick it back to them before then.

[Bohemia Feedback Tracker Ticket](https://feedback.bistudio.com/T153090)

Cannot fix what I cannot change, friend. Understand, that it's not me your looking for.

**Comment by Marshmalllow09** [comment]
I can see how people asking could be increasingly frustrating. But I read
"BI fixed dayz exp" and that doesn't tell people 'if you are running into
compatibility issues, wait for BI patch".
