### ISSUE TITLE
Vpp admin tool multiple crashes 

### ISSUE THREAD

**Issue by papa4444** [VanillaPlusPlus/VPP-Admin-Tools#66]
We are having server crashes with no error message  very regularly when using vpp , mostly when using the tp function,  also when using spectate player , is there any know fix for this,  and or what info would you need to rectify this problem

**Comment by krussedull** [comment]
same here aswell

**Comment by GravityWolfNotAmused** [comment]
Any chance it may have created a crash log?

**Comment by papa4444** [comment]
Yes it did , I've just spoken to server owner , probably best you speak to him , how would you like to communicate with him . ,here .?

**Comment by GravityWolfNotAmused** [comment]
Best if he would send it here, yes.

**Comment by JJVis** [comment]
I am also experiencing  client crashes when using the TP function. I will provide my client and server logs just for reference.
[crash_2021-02-16_20-25-17.log](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/5993331/crash_2021-02-16_20-25-17.log)
[DayZServer_x64_2021-02-16_19-08-00.txt](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/5993358/DayZServer_x64_2021-02-16_19-08-00.txt)

**Comment by GravityWolfNotAmused** [comment]
From someone using old garbage.
```
[WARNING] m_Car and m_AnimSource are left for backwards compatibility to not crash mods that are using it, but should no longer be used.
Class:      'ActionCloseCarDoors'
Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
scripts/4_World/classes\useractionscomponent\actions\interact\vehicles\actioncardoors.c:120
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:468
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:42
```

SchanaModGlobal Errors
```
------------------------------------
DESKTOP-N3NIE8J, 16.02 2021 20:27:15
Wrong parameter value
Class:      'Chat'
Function: 'AddInternal'
Stack trace:
SchanaModGlobalChat/Mission/gui\chat\chat.c:22
scripts/5_Mission/gui\chat\chat.c:123
SchanaModGlobalChat/Mission/gui\chat\chat.c:7
VPPAdminTools/5_Mission/vppadmintools\chat.c:31
scripts/5_Mission/mission\missiongameplay.c:656
scripts/3_Game/dayzgame.c:1358
```

Issue with Trader, likely in your config, but not sure:
```

------------------------------------
DESKTOP-N3NIE8J, 16.02 2021 20:29:01
NULL pointer to instance
Class:      'SurvivorBase'
Entity id:2952077

Function: 'handleSyncObjectOrientationRPC'
Stack trace:
TM/Trader/scripts/4_World/entities\dayzplayerimplement.c:573
TM/Trader/scripts/4_World/entities\dayzplayerimplement.c:393
TM/Trader/scripts/4_World/entities\dayzplayerimplement.c:68
scripts/4_World/entities\manbase\playerbase.c:4508
SchanaModAutorun/World/entities\manbase\playerbase.c:18
RadiationZone/scripts/4_World/entities\manbase\alp_playerbase.c:214
SchanaModGlobalChat/World/entities\manbase\playerbase.c:26
NewNVG/scripts/4_World/entities\manbase\playerbase.c:10
BaseBuildingPlus/scripts/4_World/overrides\playerbase.c:39
scripts/4_World/entities\manbase\playerbaseclient.c:19
scripts/3_Game/dayzgame.c:2436
JM/CF/Scripts/3_Game/communityframework\game\dayzgame.c:29
````


Only Error from VPP:
```

------------------------------------
DESKTOP-N3NIE8J, 16.02 2021 20:30:51
NULL pointer to instance
Class:      'MenuObjectManager'
Function: 'ClearBuildingSetEntries'
Stack trace:
VPPAdminTools/5_Mission/vppadmintools\gui\submenus\menuobjectmanager\menuobjectmanager.c:423
VPPAdminTools/5_Mission/vppadmintools\gui\submenus\menuobjectmanager\menuobjectmanager.c:495
JM/CF/Scripts/3_Game/communityframework\rpc\rpcmanager.c:252
scripts/3_Game/dayzgame.c:2430
JM/CF/Scripts/3_Game/communityframework\game\dayzgame.c:29
```

Now, I am wondering why it's calling ClearBuildingSetEntries. Let me look into that.

**Comment by GravityWolfNotAmused** [comment]
So, it seems that the collection of entries for the buildings is resolving null, and needed to be checked to make sure it's available before clearing, but you are stating that this is happening when people are TPing? Are there client crash logs I can peek at?

**Comment by GravityWolfNotAmused** [comment]
I have made a change to combat that specific error message: https://github.com/VanillaPlusPlus/VPP-Admin-Tools/commit/bbe1fc7c1f417cb0c3a0347c02a1c4d315731fc1

**Comment by GravityWolfNotAmused** [comment]
Any chance you can provide me script logs as well for the server, not just the crash?

**Comment by GravityWolfNotAmused** [comment]
Can you also post your mod list, so I can see if I can recreate it?

**Comment by JJVis** [comment]
absolutely. sorry was busy with some stuff. let me get that info for you.

**Comment by JJVis** [comment]
**those crassh logs were from my personal client by the way.** -  here is a list of the mods and the server info in case you wanted to join: https://www.battlemetrics.com/servers/dayz/6824671

Im just going to include an archive of all logs from server and my client. hopefully something in there will be useful and thank you for explaining those other errors to me. i appreciate it.
[Server Files.zip](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/6001904/Server.Files.zip)
[My Client files.zip](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/6001919/My.Client.files.zip)

P.S. I wasnt sure which files to include, so included multiples of logs I thought might be of assistance. Some you might have seen already.

**Comment by GravityWolfNotAmused** [comment]
This include your vpp logs?

**Comment by JJVis** [comment]
no, my bad. uploading now 
[VPP.zip](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/6005900/VPP.zip)

**Comment by papa4444** [comment]
Hi jjvis and gravity ,I originally started this post and it looks like your making some progress on a potential fix , im listening intently,  and waiting in hope

**Comment by krussedull** [comment]
I am allso crashing on tp

Last ned Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GravityWolfNotAmused** [comment]
First off, I would like to thank you for providing me everything that I have request.

# Notes:

You VPP Logs show that you have some un-favorable information located inside of your superadmins.txt, do you by chance have to extra lines in the file, or trailing/leading spaces?
```
11:55:48 | [PermissionManager] Adding Super Admin (
)
11:55:48 | [PermissionManager] Adding Super Admin (
)
```

## The first error that is mentioned in your stack traces is as follows:
```
------------------------------------
NS538228, 18.02 2021 00:53:42
NULL pointer to instance
Class:      'RPCManager'
Function: 'RPCManager'
Stack trace:
JM/CF/Scripts/3_Game/communityframework\rpc\rpcmanager.c:87
JM/CF/Scripts/3_Game/communityframework\rpc\rpcmanager.c:385
Tombstone/scripts/3_Game/*дчєнѓпфж.fxy:8
JM/CF/Scripts/3_Game/communityframework\communityframework.c:4

Runtime mode
CLI params: config serverDZ.cfg.active port 2402 profiles profiles adminlog  freezecheck  dologs  mod @CF;@VPPAdminTools;@Ear-Plugs;@Cl0uds Military Gear;@Specialist Weapon Pack;@BuilderItems;@UltimateWeaponPack;@Banking;@MoneyMod(Trader);@Trader;@zSpawnSelection;@MoreGuns;@MasssManyItemOverhaul;@VanillaPlusPlusMap;@Airdrop-Upgraded;@Modular Vest System;@Cl0uds Military Gear Expansion;@CPBWeapons;@BaseBuildingPlus;@TraderFixesAndFeatures;@Gerphelius Zil-130;@Code Lock;@DayZOresAndGems;@Camosplus;@Pen Pen Pirulin Weapon Pack;@MuchStuffPack;@CZLandroverDefender;@[Remastered] Arma Weapon Pack;@HelicopterMod-Do_Or_Die_Gaming;@RaidSchedule;@Server_Information_Panel;@PowerPoleLight;@Radiation Zone VPPM;@DoD;@Advanced Weapon Scopes;@NewClothes by rob;@CJ187-Cars;@RevGuns;@Breachingcharge;@BreachingCharge RaidSchedule Compatibility;@Breachingcharge with Notifications;@VPPNotifications;@GetShredded;@Sky_Jeep;@MoreDoors-RaidScheduleAddon;@plus200_fix_110;@Bounty_fix;@CannabisPlus;@DLC_S;@Tombstone; serverMod @CFDZPlugin;@HelicopterMod_Do_Or_Die_Gaming_SERVER;@zSpawnSelBaseAdd; 
```

First thing is first, this error points to Community Framework, and should be reported to them. Second, I notice that in the mod list for server and client in this stack trace contain a semi colon after the last mod. `;@Tombstone;` and `;@zSpawnSelBaseAdd;` The last mods in your lists do not need to end with a semi-colon, only if it's not the last one in the list.


## Second stack trace found:
```
------------------------------------
NS538228, 18.02 2021 00:54:19

[wpnfsm] R700:021037 Weapon.SaveCurrentFSMState: trying to save weapon without FSM (or uninitialized weapon) this=BoltActionRifle_Base<bd2870d0> type=R700
Class:      'BoltActionRifle_Base'
Entity id:2970240

Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
scripts/4_World/entities\firearms\weapon_base.c:361
```

This is from the weapon named R700, don't know who's it is, and don't know what it is to combat it. If it's an issue with DayZ contact BI, and if it's a modded weapon contact the modder who made it.

and the last stack trace in your server files.zip:
```
NS538228, 18.02 2021 01:52:33

[WARNING] m_Car and m_AnimSource are left for backwards compatibility to not crash mods that are using it, but should no longer be used.
Class:      'ActionCloseCarDoors'
Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
scripts/4_World/classes\useractionscomponent\actions\interact\vehicles\actioncardoors.c:120
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:468
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:42
```
This is from a vehicle that is on your server, don't know which it doesn't state, but I'd find out which and contact the person who created the content.

Inside of your client files zip:

## First Client Crash Log:
```
DESKTOP-N3NIE8J, 19.01 2021 22:32:52
NULL pointer to instance
Class:      'SchanaTraderNametagsManager'
Function: 'SchanaIsInSafezone'
Stack trace:
SchanaModTraderNametags/Mission/gui\schana_trader_nametag.c:74
SchanaModTraderNametags/Mission/nametags_manager.c:21
scripts/3_Game/dayzgame.c:2376
VPPAdminTools/3_Game/vanillaplusplus.c:41
```

This is an issue with a mode from SchanaModTraderNametags, you should reach out to them about this.

## Second Client crash log:
```
DESKTOP-N3NIE8J, 19.01 2021 22:43:10

[WARNING] m_Car and m_AnimSource are left for backwards compatibility to not crash mods that are using it, but should no longer be used.
Class:      'ActionCloseCarDoors'
Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
scripts/4_World/classes\useractionscomponent\actions\interact\vehicles\actioncardoors.c:182
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:452
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:36
```

This is once again an issue with a car that's being used on your server.

## Third Client crash log:
```
------------------------------------
DESKTOP-N3NIE8J, 19.01 2021 22:43:51

[wpnfsm] ValidateAndRepair Attempting to repair: A2MicroUzi:045814 - MagazineRepair - RBL_CLO_BU0_MA0<a86f19e0> - state: false != weapon: true
Class:      'WeaponFSM'
Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
scripts/4_World/entities\firearms\weaponfsm.c:257
scripts/4_World/entities\firearms\weaponfsm.c:225
scripts/4_World/entities\firearms\weaponfsm.c:203
scripts/4_World/entities\firearms\weaponfsm.c:36
scripts/3_Game/systems\hfsmbase.c:512
scripts/3_Game/systems\hfsmbase.c:364
scripts/4_World/entities\firearms\weapon_base.c:157
scripts/4_World/entities\firearms\fsm\states\weaponfire.c:30
scripts/4_World/systems\inventory\dayzplayerinventory.c:244
scripts/4_World/entities\dayzplayerimplement.c:656
scripts/4_World/entities\dayzplayerimplement.c:1708
ServerPanel/scripts/4_World/dayzplayerimplement.c:8
scripts/4_World/entities\manbase\playerbase.c:2374
RadiationZone/scripts/4_World/entities\manbase\alp_playerbase.c:181
```
This seems to be an issue with the weapon: A2MicroUzi

## Forth Client Crash log:
```
------------------------------------
DESKTOP-N3NIE8J, 20.01 2021 04:00:31
NULL pointer to instance
Class:      'SurvivorBase'
Entity id:2951689

Function: 'handleSyncObjectOrientationRPC'
Stack trace:
TM/Trader/scripts/4_World/entities\dayzplayerimplement.c:528
TM/Trader/scripts/4_World/entities\dayzplayerimplement.c:348
TM/Trader/scripts/4_World/entities\dayzplayerimplement.c:68
scripts/4_World/entities\manbase\playerbase.c:4511
SchanaModAutorun/World/entities\manbase\playerbase.c:18
SchanaModGlobalChat/World/entities\manbase\playerbase.c:26
RadiationZone/scripts/4_World/entities\manbase\alp_playerbase.c:214
NewNVG/scripts/4_World/entities\manbase\playerbase.c:10
BaseBuildingPlus/scripts/4_World/overrides\playerbase.c:39
scripts/4_World/entities\manbase\playerbaseclient.c:19
scripts/3_Game/dayzgame.c:2406
JM/CF/Scripts/3_Game/communityframework\game\dayzgame.c:29
```
Seems to be an issue with trader, or your configuration files for Trader.

## Fifth and Sixth Error in Crash Logs:
```
------------------------------------
DESKTOP-N3NIE8J, 20.01 2021 04:26:43
NULL pointer to instance
Class:      'MainMenu'
Function: 'OnMouseEnter'
Stack trace:
scripts/5_Mission/gui\newui\mainmenu\mainmenu.c:254
------------------------------------
DESKTOP-N3NIE8J, 20.01 2021 04:26:43
NULL pointer to instance
Class:      'MainMenu'
Function: 'OnMouseLeave'
Stack trace:
scripts/5_Mission/gui\newui\mainmenu\mainmenu.c:274
```
Issue with DayZ script, but also could be something a modder changed. Same with mouse leave.

**Comment by GravityWolfNotAmused** [comment]
Other than the change that I already made, I am in disbelief that VPP is the issue. Nothing in your VPP logs even states that you teleported near the end of the file, and also none of your errors mention VPP other than the one a first fixed. Do you have any additional information?

**Comment by GravityWolfNotAmused** [comment]
Are the users who are crashing using SSDs? Or do they have standard hard drives? If yes, How old are these drives?

**Comment by GravityWolfNotAmused** [comment]
Do these users have a profiles folder set for their client?

**Comment by JJVis** [comment]
im going by myself as a guinea pig and yes i run  dayz on an NVME actually and its about 1 1/2 years old

i have a profiles folder for my client on my local machine for testing reasons. does this cause issues? 

and once again, thank you for the insight into those other errors. some of them have been bugging me for a while.

i will reach out to schana about his mod's issues.

> Other than the change that I already made, I am in disbelief that VPP is the issue. Nothing in your VPP logs even states that you teleported near the end of the file, and also none of your errors mention VPP other than the one a first fixed. Do you have any additional information?

My admin experiences same crashing issues as me. it could be something else, you are entirely right.

**Comment by JJVis** [comment]
after more testing im in agreement with you more and more on this being a none VPP issue.

**Comment by JJVis** [comment]
for what its worth...when the client does crash , i get a "status heap error"

**Comment by DoD-Vistor** [comment]
The crashes have gone away, so Im certain it was something else.

**Comment by GravityWolfNotAmused** [comment]
I can only assume that it had to be something else, friend. Best wishes.
