### ISSUE TITLE
Heal players doesn't stop bleeding

### ISSUE THREAD

**Issue by Nazzgy** [VanillaPlusPlus/VPP-Admin-Tools#68]
the icon dissapears but player is still bleeding and can't bandage

**Comment by d146ales** [comment]
seems like an rare issue, ill try to find steps to reproduce

**Comment by GravityWolfNotAmused** [comment]
Thank you, I will also look at it on our end.

**Comment by GravityWolfNotAmused** [comment]
I have requested changes to VPPAT, and have submitted them to my partner.
If these get approved by him, then we will see this in our next patch.

**(7)**

**Comment by Da0ne** [comment]
Fixed.
