### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Qpr1me** [VanillaPlusPlus/VPP-Admin-Tools#7]
Good day! The problem is that I can’t remove some items in the game, such as the base of the wall (2 standing stobes). Tents are assembled and already installed, thanks in advance for your help!

**Comment by GravityWolfNotAmused** [comment]
Understood, will see if we can add a feature like that in the next update.

**Comment by Qpr1me** [comment]
Then the players are building in the wrong place, and illegal buildings cannot be removed. Thx

**Comment by GravityWolfNotAmused** [comment]
You're welcome.
