### ISSUE TITLE
Crashes on Teleport

### ISSUE THREAD

**Issue by lvshaman** [VanillaPlusPlus/VPP-Admin-Tools#70]
My Admin team is struggling with crashing when we teleport.  I have read the entire thread and was hoping to submit my crash logs for review.  The server never crashes .  However the local client does.
[crash_2021-03-08_19-24-19.log](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/6106048/crash_2021-03-08_19-24-19.log)

**Comment by lvshaman** [comment]
another log
[crash_2021-03-08_10-43-22.log](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/6106058/crash_2021-03-08_10-43-22.log)

**Comment by lvshaman** [comment]
another log
[crash_2021-03-08_21-38-12.log](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/files/6106121/crash_2021-03-08_21-38-12.log)

**Comment by Da0ne** [comment]
We are unable to reproduce this issue with the mod. This seems to be related to other client mods you are running along-side of this mod. After reviewing the crash logs you provided, Issue was found relating to VPPAdminTools, however it was triggered by an unknown source. Perhaps the menu was closed forcefully by another mod via script. Abruptly causing irregular behavior which leads to the crashing.

**Comment by GravityWolfNotAmused** [comment]
This issue has been reported to the creator of CF as the issue seems that their hashmap is forgetting RPCs during runtime.
