### ISSUE TITLE
Building set-problem within the Object Builder

### ISSUE THREAD

**Issue by Egobyte83** [VanillaPlusPlus/VPP-Admin-Tools#71]
As I was decorating the outskirts of Severograd on my local server, for some reason, the positioning windows (the ones that go from black to blue when you make an object the active selection) for two downed helicopter wrecks disappeared on me and now I can't remove them from the world.

Here is what happened.
Originally, there was only one wreck that I plopped down. Everything worked fine. Then, as I tried moving it around, it somehow got duplicated (!), resulting in a second wreck that had no entry in the object list to start with. I tried deleting the one wreck that had an entry in the building set, hoping that there was some sort of a dependency issue at play and that the deletion of the one that still had an entry would make both of them go away, but that only removed the positioning window for the one wreck that had it, but that wreck didn't get deleted either, so now there are TWO misplaced wrecks that I can't interact with.

![20210301050743_1](https://user-images.githubusercontent.com/33166494/110666555-baf59b80-81c9-11eb-89ec-623f9cf25497.jpg)

Help. :(

**Comment by Egobyte83** [comment]
Ok, so now one of the helicopters is actually gone. Is there some sort of delay with the object builder that is sometimes able to glitch through server restarts?

**Comment by hoffmanuel** [comment]
I have a similar issue.
First, spawned bonfires inside several building sets a while ago.
Some mod seemed to break lighting behaviour in regards to the bonfires -> deleted them and the building sets.
On the original positions, yet some of the fires remain. Is there a way to delete them without the object manager?
