### ISSUE TITLE
NOT OPENING

### ISSUE THREAD

**Issue by johnstonecooper484** [VanillaPlusPlus/VPP-Admin-Tools#74]
OKok first  you all need to know i spell like shit sorry .
ok iv got  the mod add and the key and its on server side as well as on my account side . 
now knowinf this i  have a   list of my  mods as of rite now ..
i can not get i to open at all in game :) any  thouts as to what im doing rong?

@Community-Online-Tools;@CF;@VPPAdminTools;@DayZ-Expansion;@DayZ-Expansion-Core;@DayZ-Expansion-Vehicles;@DayZ-Expansion-Licensed;@BaseBuildingPlus;@Code Lock;@Simple Base;@BuildAnywhere_v3;@PVEZ;@PVEZExpansionPlugin;@PVEZMarkersOnVPPMap;@VanillaPlusPlusMap;@Blackouts Truck Wrecks;@InventoryPlusPlus;@Better Smaller items;@BuilderItems;@SkyFall;@NoExplodingHelis;@Snap Heli To HeliPad;@FlipTransport;@ZomBerry Admin Tools;@Trolley Kart;@Trolley Kopter;@RoadTripNG;@BigWheelZ;@RaG_Hummer_Refresh;@RaG_Hummer_Armored;@Heroes And Bandits;@Heroes And Bandits PVEZ Add On;@MuchStuffPack;@Easy Signs [by Cl0ud];@Base Furniture Mods 3.0;@Chernarus Battalion Headquarters Skalisty Island

**Comment by Da0ne** [comment]
Did you follow the instructions listed on the README?
-**Added your steam64 ID in superadmins.txt?**
-**Does the steam64 ID lead to the profile you are using to play?**

**Comment by johnstonecooper484** [comment]
Yes I got it 👍 thanks 😊🙏 For reply. It turned out that I had too many
other mods in stalled in total I had a 112 that's what was causing the
problem. I now have it down to about 60. It seems to be running just fine
now. Odo I am going to revamp and see if I can knock down I've just
installing and reinstalling over and over until I get satisfied with what I
have

**Comment by GravityWolfNotAmused** [comment]
It's very common for people to just install whatever they want, and we tend to be the assholes for telling people. I am glad that you have come to this conclusion for yourself, but at this point finding a balance between stability and content is key. Keep up the good work, and best wishes.
