### ISSUE TITLE
Free Camera not working. Worked until a few hours ago, 6 April 2020.

### ISSUE THREAD

**Issue by Pardalis66** [VanillaPlusPlus/VPP-Admin-Tools#76]
Default key is backspace to work free camera.
Have been using VPP Admin builder tool all day to build a base on my home server.  Saved edits multiple times, logged in and out of server multiple times all day long, with no problems with free camera.

. as of about an hour ago or so, free camera does not work at all. Cannot go into the mode to start the camera, i.e. inside the face of your avatar, using WASD to move. that does not work at all.  you never get to the inside the avatar view.

Hitting backspace to start free cam freezes character so that only H teleport works.  Free cam does not work, mouse controls become disabled, need to log in and out to get any sense of control other than H Straight ahead. 

Server has not rebooted, no config changes, etc. logging and and out resets the ability to move with mouse, but enabling freecam, via backspace, again freezes mouse movement.     Repeatable.

**Comment by Da0ne** [comment]
Thanks for your feedback, this bug has been resolved in our internal build. Due to release either along with DayZ Patch 1.12 or when it's ready :)

**Comment by Pardalis66** [comment]
Thanks. VPPAdmin is a great mod, easy to use. Good luck.

**Comment by Pardalis66** [comment]
Seems to be working today, thanks a bunch, gents.
