### ISSUE TITLE
DZ_LightAI Not displaying

### ISSUE THREAD

**Issue by Cynntana** [VanillaPlusPlus/VPP-Admin-Tools#78]
I noticed after an up date that DayZ_LightAI no longer shows animals infected etc in esp tools. we compared t the server owners hud and his say DayZCreatureA,,,,, We cant see the rest as to the hud being small and cant expand it...  any clue what is there and why its a different option from what all the admin see?
![unknown3](https://user-images.githubusercontent.com/83528067/116803513-258dce00-aacd-11eb-8f81-f61902b98cfa.png)

**Comment by Da0ne** [comment]
Class names were changed a year ago. Rest filters.
