### ISSUE TITLE
[request] webhook send ingame time.

### ISSUE THREAD

**Issue by remy99c** [VanillaPlusPlus/VPP-Admin-Tools#79]
**Feature:**
Suggesting to add the option to send the current ingame time via the webhook feature to discord.

**Example:**
Discord Time: (webhook endpoint)
Current time: 23:00

**Context:**
My playerbase wants to know if it is night or day ingame before they start the game and enter the queue. This feature would help players that don't want to play when the server is in nighttime.

**Comment by GravityWolfNotAmused** [comment]
Hmmmm, might be something that we implement later, but at the current time it's not planned.

**Comment by kbiernat** [comment]
@remy99c you can implement this by querying your server with your bot, with valve query
check this:
https://github.com/gamedig/node-gamedig/issues/232
and this: https://python-valve.readthedocs.io/en/latest/source.html

**Comment by GravityWolfNotAmused** [comment]
Sadly not everyone has the ability to write applications, and we cannot assume that everyone has that skill or knowledge base.

**Comment by kbiernat** [comment]
I thought such pointer is better than nothing, for whoever finds this issue :)
