### ISSUE TITLE
Repair/Refill/Build button not working

### ISSUE THREAD

**Issue by AliothGaming** [VanillaPlusPlus/VPP-Admin-Tools#80]
Couldn't find anything on this other than that it only worked on vanilla car presets, was wondering if there was a fix for it, or if it only works with vanilla items. im not even sure what the full functionality of the button is meant to be, like are you supposed to be able to build walls to the different stages with it? I miss the old ESP functionality where you could select bbp wall and build it through the different stages it has.

**Comment by Da0ne** [comment]
Fixed in latest update.
