### ISSUE TITLE
[VPPAT] LOGIN ERROR

### ISSUE THREAD

**Issue by duwewi** [VanillaPlusPlus/VPP-Admin-Tools#83]
The server has no set password! Please read the
instructions found within [profile/VPPAdminTools/Permissions/credentials.txt]
on how to setup a login password. (profile is the directory where your mods configurations are generated & stored including server logs)

I cant find the TXT file with the instructions?? And also i never needed to have a PW before??
This happend after update

**Comment by Da0ne** [comment]
Read the changelogs on steam. https://steamcommunity.com/sharedfiles/filedetails/changelog/1708571078
 The READMDE.md on this github was also updated. Check the "Adding a super admin" section.

**Comment by duwewi** [comment]
Yeah but the file doent appear?
