### ISSUE TITLE
Player join webhook doesn't work

### ISSUE THREAD

**Issue by sotnikoff** [VanillaPlusPlus/VPP-Admin-Tools#84]
Player join webhook doesn't work. It works only if a player left the server.

**Comment by GravityWolfNotAmused** [comment]
@sotnikoff is this still an issue?

**Comment by GravityWolfNotAmused** [comment]
![image](https://user-images.githubusercontent.com/24533882/128382104-4dca64ac-3d26-4d82-ad49-1a0422668329.png)

I use this feature for VPPDM, and I don't see how you don't see the joins and leaves. Maybe there is another mod that is changing the same function, and breaking chain.

**Comment by GravityWolfNotAmused** [comment]
Understood, we will investigate this.

**Comment by IceDemon6** [comment]
I have this same issue on my server. Webhooks sends "Death" and "Player left", but never "Player join"

**Comment by GravityWolfNotAmused** [comment]
Thank you both for reporting, we will be looking into this issue.

**Comment by Da0ne** [comment]
Fixed with latest commit, thanks for the feedback everyone.
