### ISSUE TITLE
VPPAT ERROR txt file do not appear

### ISSUE THREAD

**Issue by duwewi** [VanillaPlusPlus/VPP-Admin-Tools#85]
My dude, u were very fast to close the tread.
I know that txt file should appear but it dont, someway i can get it from somewhere else???

**Comment by duwewi** [comment]
Nope, yes im pretty sure im looking in the right place :/
yeah i restarted twich, and it up and running with ppl in it now

**Comment by duwewi** [comment]
is it possible to add the file manually?? can i find it from somewhere else?
Lol u have discord? so i can show u?

**Comment by Da0ne** [comment]
Sure thing, join in [Discord](https://discord.dayzvpp.com )

**Comment by GravityWolfNotAmused** [comment]
Closed due to redirected to Discord.
