### ISSUE TITLE
Players can open VPP

### ISSUE THREAD

**Issue by MelvinFu** [VanillaPlusPlus/VPP-Admin-Tools#86]
Players can press the End key to open the Admin Tool and they will be asked for their password. Of course, the players have no ingame rights!

**Comment by GravityWolfNotAmused** [comment]
And it's unlikely that they have a password too. So, is your issue the fact that they can even trigger it in the first place?

**Comment by MelvinFu** [comment]
Exactly, actually the players who don't belong to any VPP group shouldn't get that far, right?

**Comment by Da0ne** [comment]
Fixed with latest commit.
