### ISSUE TITLE
VPP 

### ISSUE THREAD

**Issue by DieFX90** [VanillaPlusPlus/VPP-Admin-Tools#87]
Vpp dont show on steam soo we cant update it

**Comment by sotnikoff** [comment]
same problem here

**Comment by DieFX90** [comment]
Oki 👍🏻 Why?

søn. 8. aug. 2021 kl. 14:21 skrev Da0ne ***@***.***>:

**Comment by GravityWolfNotAmused** [comment]
Because it's back on the workshop
