### ISSUE TITLE
server problems

### ISSUE THREAD

**Issue by Qpr1me** [VanillaPlusPlus/VPP-Admin-Tools#9]
![Без имени](https://user-images.githubusercontent.com/54238266/64276460-b30fc800-cf50-11e9-819e-f366d0924d51.png)

**Comment by Qpr1me** [comment]
Sorry for the time spent, I found a mistake and solved it ... Thanks for the update!

**Comment by GravityWolfNotAmused** [comment]
You're welcome; however, don't ever be afraid or discouraged from posting bug reports, we need all bugs to be report, so thank you for sending this in our direction even though it's a user error.

**Comment by Dpatau** [comment]
@Qpr1me what was your mistake as i am getting the same error code
