### ISSUE TITLE
Cant see button label text 

### ISSUE THREAD

**Issue by codynynex** [VanillaPlusPlus/VPP-Admin-Tools#93]
I cannot see the text on the buttons. No buttons have text and others text

**Comment by Jrockbritto** [comment]
Same here [](https://imgur.com/a/YPvjeWa)

**Comment by Jrockbritto** [comment]
Same here (https://imgur.com/a/YPvjeWa)

**Comment by Da0ne** [comment]
Sorry the translation table has an issue, please use English game language until the issue is fixed.

**Comment by Jrockbritto** [comment]
Wow, thanks for the fast response!
