### ISSUE TITLE
Crash Log - Fixable?

### ISSUE THREAD

**Issue by pandora1986** [VanillaPlusPlus/VPP-Admin-Tools#97]
Hey Folks,
got the following crash log today. is this something to worry about or fixable on my end?

> ---------------------------------------------
> Log C:\DayZ-Server\server_0\DayZ\Serverprofile_namalsk\crash_2021-11-12_12-00-23.log started at 12.11. 12:00:32
> 
> 
> 
> ------------------------------------
> DAYZSERVER, 12.11 2021 12:00:32
> Wrong parameter value
> Class:      'CustomMission'
> Function: 'Get'
> Stack trace:
> scripts/1_Core/proto\enstring.c:408
> VPPAdminTools/5_Mission/vppadmintools\missionserver.c:267
> VPPAdminTools/5_Mission/vppadmintools\missionserver.c:38
> nst/ns_dayz/scripts/5_Mission/namalsksurvival\mission\missionserver.c:8
> $CurrentDir:mpmissions\hardcore.namalsk\init.c:56
> 
> Runtime mode
> CLI params: instanceId 1 config serverDZ_0.cfg profiles Serverprofile_namalsk port 2302 cpuCount 4 noFilePatching  dologs  adminlog  freezecheck  mod @CF;@Namalsk Island;@Namalsk Survival;@VPPAdminTools;

**Comment by GravityWolfNotAmused** [comment]
Looks like you messed up a parameter in your CLI

**Comment by pandora1986** [comment]
any idea what exactly? using the cli param for over 2 years without issues
this is a fresh namalsk setup with only 4 mods and vanilla namalsk settings

**Comment by GravityWolfNotAmused** [comment]
![image](https://user-images.githubusercontent.com/24533882/141489654-1034f05a-bf2e-427f-b2c8-f8072791ddd1.png)

That's the line from the error, it seems that it's failing to get the line from server cfg.

What has changed recently?

**Comment by pandora1986** [comment]
oh man, such a silly thing, your screenshoot says "parse and find server name", so i looked into the cfg and i hat a ";" missing at the end of the line --> error gone!
thanks for your quick response

**Comment by GravityWolfNotAmused** [comment]
<3 Enjoy your day, glad I could help.
